-- TPSDBCORE01 | AUDIENCE DOMAIN | R1 | NOT DEPLOYED
CREATE TABLE tps_audience_observation (
    audience_observation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    segment_entity_id     NUMBER,
    channel_entity_id     NUMBER,
    context_id            NUMBER,
    observed_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    metric_code           VARCHAR2(100) NOT NULL,
    metric_value          NUMBER NOT NULL,
    sample_size           NUMBER,
    source_id             NUMBER,
    attributes_json       JSON,
    CONSTRAINT fk_tps_audobs_segment FOREIGN KEY(segment_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_audobs_channel FOREIGN KEY(channel_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_audobs_context FOREIGN KEY(context_id) REFERENCES tps_context(context_id),
    CONSTRAINT fk_tps_audobs_source FOREIGN KEY(source_id) REFERENCES tps_source(source_id)
);
CREATE INDEX ix_tps_audobs_time ON tps_audience_observation(channel_entity_id,observed_at,metric_code);
