-- TPSDBCORE01 | CORE-03 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_entity_type (
    entity_type_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    type_code            VARCHAR2(100) NOT NULL,
    display_name         VARCHAR2(200) NOT NULL,
    parent_type_id       NUMBER NULL,
    description          VARCHAR2(1000),
    lifecycle_state      VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_entity_type_code UNIQUE (type_code),
    CONSTRAINT fk_tps_entity_type_parent FOREIGN KEY (parent_type_id) REFERENCES tps_entity_type(entity_type_id),
    CONSTRAINT ck_tps_entity_type_state CHECK (lifecycle_state IN ('ACTIVE','INACTIVE','DEPRECATED','RETIRED'))
);
