/*=============================================================================
 @file              src/02-kernel/200_tps_entity_type.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-03
 @workstream        WS-04 Identity kernel
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE
 @purpose           Define the canonical hierarchical taxonomy used to classify
                    every universal TPS_ENTITY without creating separate identity
                    tables per application, radio, TV or business domain.
 @business_impact   Provides one corporate type authority for PERSON, ORGANIZATION,
                    MEDIA, LOCATION, AUDIENCE, EVENT, CONTRACT, DEVICE, SERVICE,
                    CAMPAIGN, KNOWLEDGE, AI_ENTITY and their future subtypes.
 @objects           Creates table TPS_ENTITY_TYPE and its PK/UK/FK/CHECK constraints.
 @dependencies      None at object-creation time; self-reference resolves within
                    TPS_ENTITY_TYPE.
 @upstream          Approved entity ontology and `docs/06-data-dictionary/ENTITY-DICTIONARY.md`.
 @downstream        TPS_ENTITY, TPS_RELATION_TYPE source/target constraints,
                    reference data, D3KA validation, graph labels and APIs.
 @d3ka_role         ENTITY
 @d3ka_links        Defines the allowed entity classes used on D3KA S and T axes.
 @ai_role           AI may classify/propose entity types, but type definitions are
                    governed reference data and not autonomously authoritative.
 @security          Taxonomy metadata is non-secret but changes affect global data
                    semantics. Write access must be restricted to controlled admin/
                    migration authority; runtime consumers should read only.
 @performance       Small reference table. Unique lookup on TYPE_CODE and PK lookup
                    on ENTITY_TYPE_ID are dominant paths. Parent traversal depth is
                    expected to be small; recursive queries must be benchmarked if
                    taxonomy grows materially.
 @transaction       DDL performs Oracle implicit commit when deployed. This source
                    contains no application DML and owns no runtime commit logic.
 @idempotency       CREATE TABLE is not directly idempotent. Deployment is controlled
                    by versioned migration/precheck and object-existence validation.
 @failure_modes     Existing object/name conflict, invalid privilege, tablespace/
                    quota restrictions, or invalid FK definition. Deployment must
                    fail closed and not continue to dependent kernel objects.
 @rollback_recovery Before production data references it, rollback is controlled
                    DROP TABLE ... CASCADE CONSTRAINTS under approved migration.
                    After use, removal becomes stateful/destructive and requires R3
                    migration/recovery planning rather than blind DROP.
 @tests             tests/unit/UT-001_entity_constraints.sql; D3KA type-validation
                    tests consume this table indirectly.
 @evidence          CORE-03 object/constraint evidence and CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: CREATE TABLE,
                    identity columns, constraints and TIMESTAMP WITH TIME ZONE.
 @links             PROJECT-MAP.md; SOURCE-MAP.md; ENTITY-DICTIONARY.md;
                    ADR-0003-ONE-RELATIONAL-AUTHORITY.md;
                    src/02-kernel/210_tps_entity.sql;
                    src/03-d3ka/300_tps_relation_type.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one governed entity type in the corporate ontology.
CREATE TABLE tps_entity_type (
    -- Surrogate immutable database identity for FK use.
    entity_type_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    -- Stable machine key. This is the contract-facing identifier, not display text.
    type_code            VARCHAR2(100) NOT NULL,
    -- Human-readable label; may evolve without changing TYPE_CODE semantics.
    display_name         VARCHAR2(200) NOT NULL,
    -- Optional taxonomy parent, enabling hierarchical type reasoning.
    parent_type_id       NUMBER NULL,
    description          VARCHAR2(1000),
    -- Lifecycle protects consumers from silently reusing deprecated semantics.
    lifecycle_state      VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_entity_type_code UNIQUE (type_code),
    CONSTRAINT fk_tps_entity_type_parent FOREIGN KEY (parent_type_id) REFERENCES tps_entity_type(entity_type_id),
    CONSTRAINT ck_tps_entity_type_state CHECK (lifecycle_state IN ('ACTIVE','INACTIVE','DEPRECATED','RETIRED'))
);
