-- TPSDBCORE01 | CORE-03 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_entity (
    entity_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_type_id       NUMBER NOT NULL,
    canonical_key        VARCHAR2(300) NOT NULL,
    canonical_name       VARCHAR2(500) NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    attributes_json      JSON,
    valid_from           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to             TIMESTAMP WITH TIME ZONE,
    superseded_by_id     NUMBER,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    created_by           VARCHAR2(128) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
    updated_by           VARCHAR2(128) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
    row_version          NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT uk_tps_entity_key UNIQUE (canonical_key),
    CONSTRAINT fk_tps_entity_type FOREIGN KEY (entity_type_id) REFERENCES tps_entity_type(entity_type_id),
    CONSTRAINT fk_tps_entity_superseded FOREIGN KEY (superseded_by_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_entity_state CHECK (state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_tps_entity_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);
