/*=============================================================================
 @file              src/02-kernel/210_tps_entity.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-03
 @workstream        WS-04 Identity kernel
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before business use; R3_TRANSFORMATIVE after use
 @purpose           Create the universal canonical identity table for every
                    identifiable corporate/media object. This is the common vertex
                    authority for the D3KA and Property Knowledge Graph.
 @business_impact   Prevents duplicate identities such as separate RADIO_ARTIST,
                    TV_ARTIST and PODCAST_ARTIST records for the same real entity.
                    Enables one identity to participate in many roles/relationships.
 @objects           Creates TPS_ENTITY with PK, unique canonical key, type FK,
                    supersession self-FK and lifecycle/temporal checks.
 @dependencies      TPS_ENTITY_TYPE.
 @upstream          Entity ingestion/resolution processes, governed reference type
                    catalog, approved application/API ingestion paths.
 @downstream        TPS_PROPERTY, TPS_SOURCE.source_entity_id, TPS_RELATION S/T axes,
                    TPS_ASSERTION, VECTOR, media/commercial/rights/audience domain
                    extensions, Property Graph, API/JSON projections and AI retrieval.
 @d3ka_role         ENTITY
 @d3ka_links        ENTITY_ID is the canonical identifier used by SOURCE_ENTITY_ID
                    and TARGET_ENTITY_ID; ENTITY_TYPE_ID constrains semantic validity.
 @ai_role           AI may resolve, rank or propose entity matches, but entity
                    identity creation/merge/supersession remains governed and auditable.
 @security          Entity records may represent people/organizations and therefore
                    later carry sensitive relationships. Direct DML must be restricted;
                    ATTRIBUTES_JSON must not become an uncontrolled secret store.
 @performance       High-cardinality core table. Dominant access paths are PK lookup,
                    CANONICAL_KEY lookup, ENTITY_TYPE_ID filtering and state filtering.
                    Future indexes must be justified by measured workload.
 @transaction       DDL has Oracle implicit commit when deployed. Row-level runtime
                    transaction policy belongs to ingestion/services, not this DDL.
 @idempotency       CREATE TABLE is not directly idempotent; controlled migration only.
 @failure_modes     Missing TPS_ENTITY_TYPE, duplicate object, privilege/quota error,
                    invalid constraint definition. Deployment must stop before
                    dependent D3KA/domain objects are applied.
 @rollback_recovery Before use, controlled DROP is possible. Once identities exist,
                    destructive rollback is prohibited without export/restore or
                    forward migration preserving identity and history.
 @tests             tests/unit/UT-001_entity_constraints.sql;
                    tests/performance/PERF-001_entity_lookup.sql;
                    tests/D3KA/D3KA-001_assert_relation.sql and related D3KA tests.
 @evidence          CORE-03 identity-kernel evidence, CORE-15 D3KA evidence,
                    CORE-17 performance evidence, CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: CREATE TABLE,
                    JSON data type, identity columns, constraints, temporal datatypes.
 @links             docs/06-data-dictionary/ENTITY-DICTIONARY.md;
                    docs/04-d3ka/D3KA-ENGINEERING-SPEC-v0.02.md;
                    src/02-kernel/200_tps_entity_type.sql;
                    src/03-d3ka/310_tps_relation.sql;
                    src/06-graph/600_tps_media_knowledge_graph.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one canonical entity identity, independent of application/channel role.
CREATE TABLE tps_entity (
    entity_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    -- Governs the semantic class of this entity and its admissible D3KA relations.
    entity_type_id       NUMBER NOT NULL,
    -- Stable global business/application key. Uniqueness prevents parallel identity.
    canonical_key        VARCHAR2(300) NOT NULL,
    canonical_name       VARCHAR2(500) NOT NULL,
    -- Lifecycle is explicit so superseded/retired identities are never silently reused.
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    -- Flexible attributes only; relationally important facts/links belong in governed
    -- columns, TPS_PROPERTY or TPS_RELATION rather than uncontrolled JSON duplication.
    attributes_json      JSON,
    valid_from           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to             TIMESTAMP WITH TIME ZONE,
    -- Identity resolution may supersede a record while preserving historical references.
    superseded_by_id     NUMBER,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    created_by           VARCHAR2(128) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
    updated_by           VARCHAR2(128) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
    -- Optimistic version marker reserved for controlled update semantics.
    row_version          NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT uk_tps_entity_key UNIQUE (canonical_key),
    CONSTRAINT fk_tps_entity_type FOREIGN KEY (entity_type_id) REFERENCES tps_entity_type(entity_type_id),
    CONSTRAINT fk_tps_entity_superseded FOREIGN KEY (superseded_by_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_entity_state CHECK (state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_tps_entity_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);
