-- TPSDBCORE01 | CORE-03 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_property (
    property_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_id            NUMBER NOT NULL,
    property_key         VARCHAR2(200) NOT NULL,
    property_value       JSON NOT NULL,
    value_class          VARCHAR2(30) DEFAULT 'DECLARED' NOT NULL,
    valid_from           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to             TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_property_entity FOREIGN KEY (entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_property_value_class CHECK (value_class IN ('DECLARED','OBSERVED','DERIVED','AI_GENERATED')),
    CONSTRAINT ck_tps_property_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);
