/*=============================================================================
 @file              src/02-kernel/220_tps_property.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-03/06/07/09
 @workstream        WS-04 Identity kernel / WS-07 Context / WS-08 Temporal /
                    WS-10 Knowledge assertions
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before use; R3_TRANSFORMATIVE after property history exists
 @purpose           Provide temporally valid, extensible JSON-valued properties for a
                    canonical TPS_ENTITY without requiring a physical column for every
                    future attribute and without confusing properties with relations.
 @business_impact   Allows new descriptive facts for artists, programs, stations,
                    media assets, advertisers and other entities while preserving one
                    universal identity model and temporal history.
 @objects           Creates TPS_PROPERTY with PK, entity FK, value-class and temporal checks.
 @dependencies      TPS_ENTITY.
 @upstream          Governed ingestion, observation, derivation and approved AI-generated
                    property pipelines.
 @downstream        D3KA enriched properties, API projections, analytics, AI/RAG retrieval,
                    temporal reconstruction and audit/provenance workflows.
 @d3ka_role         ENTITY/PROPERTIES/TEMPORAL
 @d3ka_links        Supplies P enrichment for entities participating on D3KA S/T axes.
                    It does not replace TPS_RELATION for inter-entity semantics.
 @ai_role           AI-generated values are explicitly classed `AI_GENERATED`; such values
                    must not silently become authoritative facts without provenance/
                    verification policy outside this table.
 @security          JSON values may contain sensitive attributes. Classification,
                    least-privilege access and redaction rules are required before
                    production ingestion of sensitive/person data.
 @performance       Potentially high-row-count EAV-like table. Common access path is
                    ENTITY_ID plus PROPERTY_KEY plus current temporal state. Indexing
                    must be workload-driven to avoid write amplification.
 @transaction       DDL implicit commit on deployment. Runtime writers own DML transaction;
                    this table does not autonomously commit.
 @idempotency       CREATE TABLE is not directly idempotent; migration framework required.
 @failure_modes     Missing TPS_ENTITY, invalid JSON, invalid value class, invalid validity
                    interval, privilege/quota failure. Consumers must not infer property
                    absence as false unless domain rules explicitly define that behavior.
 @rollback_recovery Before use, table can be removed via controlled rollback. After history
                    exists, preserve/export history and migrate forward rather than DROP.
 @tests             future property-specific unit/temporal tests; existing entity and
                    D3KA temporal suites provide partial indirect coverage.
 @evidence          CORE-03/06/07/09 object/constraint/temporal evidence and CORE-20 closure.
 @references        Oracle AI Database 26ai SQL Language Reference: JSON data type,
                    CREATE TABLE, constraints, TIMESTAMP WITH TIME ZONE.
 @links             ENTITY-DICTIONARY.md; D3KA-ENGINEERING-SPEC-v0.02.md;
                    src/02-kernel/210_tps_entity.sql; src/03-d3ka/310_tps_relation.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one typed temporal property value attached to one canonical entity.
CREATE TABLE tps_property (
    property_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_id            NUMBER NOT NULL,
    -- Stable semantic property key governed by application/domain contracts.
    property_key         VARCHAR2(200) NOT NULL,
    -- JSON supports scalar or structured value while avoiding uncontrolled schema churn.
    property_value       JSON NOT NULL,
    -- Records how the value entered knowledge space; not a trust/verification substitute.
    value_class          VARCHAR2(30) DEFAULT 'DECLARED' NOT NULL,
    valid_from           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to             TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_property_entity FOREIGN KEY (entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_property_value_class CHECK (value_class IN ('DECLARED','OBSERVED','DERIVED','AI_GENERATED')),
    CONSTRAINT ck_tps_property_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);
