/*=============================================================================
 @file              src/02-kernel/230_tps_source.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-09
 @workstream        WS-10 Knowledge assertions / provenance
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before use; R3_TRANSFORMATIVE after evidence references exist
 @purpose           Register the provenance origin of facts, observations, imports,
                    documents, events, APIs, sensors, systems, humans and AI models so
                    that knowledge can be traced to evidence rather than treated as
                    anonymous truth.
 @business_impact   Enables auditability of journalism, rights, schedules, audience,
                    commercial facts and AI inferences; supports the question "where did
                    this information come from?" across the corporate knowledge graph.
 @objects           Creates TPS_SOURCE with PK, unique source key, optional entity FK,
                    source-class/trust checks and optional URI/SHA-256 metadata.
 @dependencies      TPS_ENTITY when SOURCE_ENTITY_ID is used.
 @upstream          Import pipelines, documents, APIs, systems, human verification,
                    sensors/events and registered AI model metadata.
 @downstream        TPS_RELATION.provenance_source_id, TPS_ASSERTION, AI decision ledger,
                    audit/certification and Graph-RAG evidence retrieval.
 @d3ka_role         PROVENANCE
 @d3ka_links        Supplies E/evidence enrichment for D3KA cells and assertions.
 @ai_role           AI models can be registered as `AI_MODEL` sources. Registration does
                    not make model output authoritative; downstream confidence and
                    verification class remain mandatory.
 @security          SOURCE_URI may expose internal locations and must not contain embedded
                    credentials. Hashes are identifiers/integrity evidence, not secrets.
                    Write authority is governance/ingest only; applications read via APIs.
 @performance       Reference/evidence registry expected to grow slower than event/fact
                    tables. Dominant paths: SOURCE_KEY unique lookup, SOURCE_ENTITY_ID,
                    SOURCE_CLASS and hash-assisted evidence correlation when indexed.
 @transaction       DDL implicit commit on deployment; runtime source registration is
                    caller-owned transaction and must not be silently committed here.
 @idempotency       CREATE TABLE is non-idempotent; SOURCE_KEY uniqueness supports
                    application-level idempotent source registration.
 @failure_modes     Missing TPS_ENTITY for entity-backed source, duplicate SOURCE_KEY,
                    invalid source/trust class, privilege/quota error. Trust level
                    `UNASSESSED` must not be interpreted as trusted.
 @rollback_recovery Before use, controlled DROP is possible. After references exist,
                    preserve provenance identities and migrate forward; deleting source
                    rows can break audit/evidence lineage and is not normal rollback.
 @tests             D3KA provenance-required tests; AI inference verification tests;
                    future source-registry unit tests.
 @evidence          CORE-09 provenance/assertion evidence; CORE-12 audit evidence;
                    CORE-16 AI grounding evidence; CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Reference: CREATE TABLE, constraints,
                    JSON; cryptographic SHA-256 is stored only as supplied evidence metadata.
 @links             docs/06-data-dictionary/OBJECT-CATALOG.md;
                    docs/04-d3ka/D3KA-ENGINEERING-SPEC-v0.02.md;
                    src/02-kernel/210_tps_entity.sql; src/03-d3ka/310_tps_relation.sql;
                    src/08-knowledge/810_tps_assertion.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one stable provenance/evidence source identity.
CREATE TABLE tps_source (
    source_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    source_key           VARCHAR2(300) NOT NULL,
    source_class         VARCHAR2(40) NOT NULL,
    -- Optional link when the provenance source is itself a canonical TPS_ENTITY.
    source_entity_id     NUMBER,
    -- Locator only. Credentials/secrets are prohibited in this value.
    source_uri           VARCHAR2(2000),
    -- Optional content/evidence integrity fingerprint supplied by the ingest process.
    source_hash_sha256   VARCHAR2(64),
    -- Governance assessment, deliberately defaulting to UNASSESSED/fail-nontrust.
    trust_level          VARCHAR2(30) DEFAULT 'UNASSESSED' NOT NULL,
    attributes_json      JSON,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_source_key UNIQUE (source_key),
    CONSTRAINT fk_tps_source_entity FOREIGN KEY (source_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_source_class CHECK (source_class IN ('HUMAN','SYSTEM','DOCUMENT','EVENT','IMPORT','API','AI_MODEL','SENSOR','OTHER')),
    CONSTRAINT ck_tps_source_trust CHECK (trust_level IN ('UNASSESSED','LOW','MEDIUM','HIGH','AUTHORITATIVE'))
);
