-- TPSDBCORE01 | CORE-09 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_source (
    source_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    source_key           VARCHAR2(300) NOT NULL,
    source_class         VARCHAR2(40) NOT NULL,
    source_entity_id     NUMBER,
    source_uri           VARCHAR2(2000),
    source_hash_sha256   VARCHAR2(64),
    trust_level          VARCHAR2(30) DEFAULT 'UNASSESSED' NOT NULL,
    attributes_json      JSON,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_source_key UNIQUE (source_key),
    CONSTRAINT fk_tps_source_entity FOREIGN KEY (source_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_source_class CHECK (source_class IN ('HUMAN','SYSTEM','DOCUMENT','EVENT','IMPORT','API','AI_MODEL','SENSOR','OTHER')),
    CONSTRAINT ck_tps_source_trust CHECK (trust_level IN ('UNASSESSED','LOW','MEDIUM','HIGH','AUTHORITATIVE'))
);
