/*=============================================================================
 @file              src/04-context/400_tps_context_type.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-06
 @workstream        WS-07 Context engine
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before context use; R3 after semantic history depends on IDs
 @purpose           Define stable context-dimension types used to qualify D3KA relations and
                    other domain facts without hard-coding every contextual dimension as a column.
 @business_impact   Enables one relationship/content decision to vary by station, channel,
                    program, audience, location, device, event, rights, commercial or operational context.
 @objects           Creates TPS_CONTEXT_TYPE with PK and unique TYPE_CODE.
 @dependencies      None.
 @upstream          CONTEXT-DICTIONARY and approved context architecture.
 @downstream        TPS_CONTEXT and D3KA relation-type/context validation.
 @d3ka_role         CONTEXT
 @d3ka_links        Defines C-dimension taxonomy used by TPS_CONTEXT and TPS_RELATION.CONTEXT_ID.
 @ai_role           AI may use contexts in retrieval/recommendation; context type ontology is governed.
 @security          Some context types can imply location/audience/privacy sensitivity; the type catalog
                    itself is non-secret but access to context instances may require restriction.
 @performance       Small reference table; TYPE_CODE unique lookup is dominant path.
 @transaction       DDL implicit commit; no runtime transaction behavior.
 @idempotency       CREATE TABLE non-idempotent; TYPE_CODE unique stable identity.
 @failure_modes     Duplicate type code/privilege error. Undefined context types block governed context creation.
 @rollback_recovery Before use controlled drop; after use preserve IDs and migrate/supersede taxonomy.
 @tests             Context-specific type/FK tests pending; D3KA-003_require_context uses context semantics indirectly.
 @evidence          CORE-06 context model evidence and CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: CREATE TABLE, constraints.
 @links             docs/06-data-dictionary/CONTEXT-DICTIONARY.md;
                    src/04-context/410_tps_context.sql;
                    src/03-d3ka/310_tps_relation.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one governed category of context dimension/value.
CREATE TABLE tps_context_type (
    context_type_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    type_code            VARCHAR2(100) NOT NULL,
    display_name         VARCHAR2(200) NOT NULL,
    description          VARCHAR2(1000),
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_context_type_code UNIQUE (type_code)
);
