-- TPSDBCORE01 | CORE-06 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_context_type (
    context_type_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    type_code            VARCHAR2(100) NOT NULL,
    display_name         VARCHAR2(200) NOT NULL,
    description          VARCHAR2(1000),
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_context_type_code UNIQUE (type_code)
);
