/*=============================================================================
 @file              src/04-context/410_tps_context.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-06/07
 @workstream        WS-07 Context engine / WS-08 Temporal engine
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before use; R3_TRANSFORMATIVE after context history exists
 @purpose           Persist stable, typed and temporally valid context instances encoded as
                    governed JSON, providing the C dimension used by D3KA relations and domain logic.
 @business_impact   Allows the same entity/relation/content to carry different meaning or validity
                    by region, station, program, audience, device, weather/event, commercial,
                    regulatory, rights or operational situation.
 @objects           Creates TPS_CONTEXT with PK/UK/FK/state/validity constraints.
 @dependencies      TPS_CONTEXT_TYPE.
 @upstream          Governed context creation/resolution and reference/import pipelines.
 @downstream        TPS_RELATION.CONTEXT_ID, rights grants, events, policy/AI retrieval and APIs.
 @d3ka_role         CONTEXT/TEMPORAL
 @d3ka_links        CONTEXT_ID is the C enrichment of a D3KA S/R/T cell; VALID_FROM/VALID_TO
                    provide context-level temporal validity independent of relation validity.
 @ai_role           AI may select/derive candidate context, but authoritative context creation and
                    use in policy-sensitive decisions require governed provenance/rules outside this table.
 @security          CONTEXT_JSON may contain location/audience/operationally sensitive data; direct
                    access must follow classification and least privilege. Secrets are prohibited.
 @performance       Potentially moderate/high reference set. Dominant access: CONTEXT_KEY unique lookup,
                    CONTEXT_TYPE_ID/state/time filtering. JSON search indexes only after workload evidence.
 @transaction       DDL implicit commit; runtime context DML belongs to caller transaction.
 @idempotency       CREATE TABLE non-idempotent; CONTEXT_KEY supports stable idempotent identity.
 @failure_modes     Duplicate context key, invalid type/state/time/JSON. No schema is enforced on
                    CONTEXT_JSON by this DDL; type-specific JSON contracts/tests are required before
                    context types are treated as complete.
 @rollback_recovery Before use controlled drop; after referenced by relations/events/rights, preserve
                    context identity/history and migrate/supersede instead of destructive deletion.
 @tests             Context-specific schema/temporal tests pending; D3KA context-required tests and
                    rights/event FK tests provide partial indirect coverage.
 @evidence          CORE-06 context evidence; CORE-07 temporal evidence; CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: JSON, constraints, temporal types.
 @links             docs/06-data-dictionary/CONTEXT-DICTIONARY.md;
                    src/04-context/400_tps_context_type.sql;
                    src/03-d3ka/310_tps_relation.sql;
                    src/09-event/910_tps_event.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one stable typed context instance with optional validity lifecycle.
CREATE TABLE tps_context (
    context_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    context_type_id      NUMBER NOT NULL,
    -- Stable key used by applications/imports; JSON content may evolve under governed semantics.
    context_key          VARCHAR2(300) NOT NULL,
    context_json         JSON NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    valid_from           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to             TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_context_key UNIQUE (context_key),
    CONSTRAINT fk_tps_context_type FOREIGN KEY (context_type_id) REFERENCES tps_context_type(context_type_id),
    CONSTRAINT ck_tps_context_state CHECK (state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_tps_context_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);
