-- TPSDBCORE01 | CORE-06 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_context (
    context_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    context_type_id      NUMBER NOT NULL,
    context_key          VARCHAR2(300) NOT NULL,
    context_json         JSON NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    valid_from           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to             TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_context_key UNIQUE (context_key),
    CONSTRAINT fk_tps_context_type FOREIGN KEY (context_type_id) REFERENCES tps_context_type(context_type_id),
    CONSTRAINT ck_tps_context_state CHECK (state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_tps_context_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);
