-- TPSDBCORE01 | PROGRAMMING DOMAIN | R1 | NOT DEPLOYED
CREATE TABLE tps_schedule (
    schedule_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    schedule_key          VARCHAR2(300) NOT NULL,
    owner_entity_id       NUMBER NOT NULL,
    timezone_name         VARCHAR2(100) NOT NULL,
    precedence            NUMBER DEFAULT 100 NOT NULL,
    schedule_class        VARCHAR2(30) NOT NULL,
    state                 VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL,
    valid_from            TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_to              TIMESTAMP WITH TIME ZONE,
    attributes_json       JSON,
    CONSTRAINT uk_tps_schedule_key UNIQUE(schedule_key),
    CONSTRAINT fk_tps_schedule_owner FOREIGN KEY(owner_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_schedule_class CHECK(schedule_class IN ('NETWORK','STATION','CHANNEL','LOCAL_OVERRIDE','EMERGENCY','FALLBACK')),
    CONSTRAINT ck_tps_schedule_state CHECK(state IN ('DRAFT','APPROVED','ACTIVE','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_tps_schedule_validity CHECK(valid_to IS NULL OR valid_to > valid_from)
);
