-- TPSDBCORE01 | PROGRAMMING DOMAIN | R1 | NOT DEPLOYED
CREATE TABLE tps_schedule_item (
    schedule_item_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    schedule_id           NUMBER NOT NULL,
    content_entity_id     NUMBER NOT NULL,
    context_id            NUMBER,
    start_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    item_class            VARCHAR2(30) NOT NULL,
    priority              NUMBER DEFAULT 100 NOT NULL,
    state                 VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    attributes_json       JSON,
    CONSTRAINT fk_tps_scheditem_schedule FOREIGN KEY(schedule_id) REFERENCES tps_schedule(schedule_id),
    CONSTRAINT fk_tps_scheditem_content FOREIGN KEY(content_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_scheditem_context FOREIGN KEY(context_id) REFERENCES tps_context(context_id),
    CONSTRAINT ck_tps_scheditem_time CHECK(end_at > start_at),
    CONSTRAINT ck_tps_scheditem_class CHECK(item_class IN ('PROGRAM','CONTENT','LIVE','COMMERCIAL','JINGLE','PROMO','FILLER','EMERGENCY')),
    CONSTRAINT ck_tps_scheditem_state CHECK(state IN ('ACTIVE','CANCELLED','SUPERSEDED','PLAYED','SKIPPED'))
);
CREATE INDEX ix_tps_scheditem_time ON tps_schedule_item(schedule_id,start_at,end_at,state);
