-- TPSDBCORE01 | MEDIA ASSET DOMAIN | R1 | NOT DEPLOYED
CREATE TABLE tps_media_asset (
    media_asset_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    asset_entity_id       NUMBER NOT NULL,
    content_entity_id     NUMBER,
    sha256_hex            VARCHAR2(64) NOT NULL,
    mime_type             VARCHAR2(200),
    codec_video           VARCHAR2(100),
    codec_audio           VARCHAR2(100),
    bitrate_bps           NUMBER,
    width_px              NUMBER,
    height_px             NUMBER,
    duration_ms           NUMBER,
    size_bytes            NUMBER,
    storage_location      VARCHAR2(2000) NOT NULL,
    lifecycle_state       VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    technical_json        JSON,
    created_at            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_media_asset_hash_location UNIQUE(sha256_hex, storage_location),
    CONSTRAINT fk_tps_media_asset_entity FOREIGN KEY(asset_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_media_content_entity FOREIGN KEY(content_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_media_asset_state CHECK(lifecycle_state IN ('ACTIVE','ARCHIVED','MISSING','SUPERSEDED','RETIRED'))
);
