/*=============================================================================
 @file              src/12-media/1270_tps_continuity_decision.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-12/14/18
 @workstream        Media continuity / audit / playout decision ledger
 @source_state      SOURCE_READY_PENDING_RUNTIME_COMPILE_TEST
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before data; R3_TRANSFORMATIVE after audit history exists
 @purpose           Persist every deterministic continuity resolution so the system can prove
                    why a station/channel continued with primary, local emergency/fallback,
                    network programming or no playable item.
 @business_impact   Provides auditability for 24x7 continuity and affiliate/network failover.
 @objects           Creates TPS_CONTINUITY_DECISION plus lookup index.
 @dependencies      TPS_ENTITY and TPS_SCHEDULE_ITEM.
 @upstream          TPS_CONTINUITY_PKG.RESOLVE_PLAYOUT.
 @downstream        Audit, incident analysis, AI explanations, operations dashboards and certification.
 @d3ka_role         EVENT/POLICY/TEMPORAL
 @d3ka_links        OWNER/NETWORK are canonical entities; selected schedule item is the resolved
                    temporal programming action derived from D3KA network relationships.
 @ai_role           AI may inspect/explain decisions but cannot rewrite historical rows.
 @security          Operationally sensitive audit metadata. INSERT only through continuity package;
                    UPDATE/DELETE blocked by immutable trigger except extraordinary DBA recovery.
 @performance       Append-oriented low/medium-rate decision ledger. Index supports owner/time analysis.
 @transaction       Insert participates in caller transaction; no autonomous transaction in table DDL.
 @idempotency       Each resolution is a new decision event; callers needing request idempotency must later
                    supply a request/correlation key. Current table does not deduplicate retries.
 @failure_modes     Invalid entity/item FK, invalid primary flag/decision code, storage/privilege error.
 @rollback_recovery Uncommitted insert can rollback. Committed audit rows are append-only history;
                    corrections are represented by subsequent decisions/events, not updates.
 @tests             tests/continuity/CONT-001_local_fallback.sql;
                    CONT-002_network_fallback.sql; CONT-003_immutable_ledger.sql.
 @evidence          CORE-12 audit, CORE-14 continuity, CORE-18 privilege/integrity evidence.
 @references        Oracle AI Database 26ai SQL Language Reference: CREATE TABLE, JSON, constraints.
 @links             src/12-media/1271_tps_continuity_decision_immutable_trg.sql;
                    src/12-media/1281_tps_continuity_pkg.pkb
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — initial continuity decision ledger.
=============================================================================*/

CREATE TABLE tps_continuity_decision (
    continuity_decision_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    owner_entity_id        NUMBER NOT NULL,
    evaluated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    primary_available      NUMBER(1) NOT NULL,
    network_entity_id      NUMBER,
    selected_schedule_item_id NUMBER,
    decision_code          VARCHAR2(40) NOT NULL,
    reason_json            JSON,
    created_at             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    created_by             VARCHAR2(128) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
    CONSTRAINT fk_tps_cont_owner FOREIGN KEY(owner_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_cont_network FOREIGN KEY(network_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_cont_item FOREIGN KEY(selected_schedule_item_id) REFERENCES tps_schedule_item(schedule_item_id),
    CONSTRAINT ck_tps_cont_primary CHECK(primary_available IN (0,1)),
    CONSTRAINT ck_tps_cont_decision CHECK(decision_code IN (
        'PRIMARY','LOCAL_SCHEDULE','LOCAL_EMERGENCY','LOCAL_FALLBACK',
        'NETWORK_SCHEDULE','NETWORK_FALLBACK','NO_PLAYABLE_ITEM'
    ))
);

CREATE INDEX ix_tps_cont_owner_time
    ON tps_continuity_decision(owner_entity_id, evaluated_at);
