/*=============================================================================
 @file              src/10-policy/1000_tps_policy.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-11
 @workstream        WS-12 Policy/rules
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before policy data; R3_TRANSFORMATIVE after policy history exists
 @purpose           Define governed policy identities, domains, priority and temporal lifecycle
                    for deterministic decision rules that constrain media/AI operations.
 @business_impact   Establishes a central policy authority so business/legal/operational
                    constraints are not duplicated inside applications or probabilistic AI.
 @objects           Creates TPS_POLICY with PK, unique policy key and state/validity checks.
 @dependencies      None.
 @upstream          Approved business rules, compliance/security/rights architecture and ADRs.
 @downstream        TPS_RULE and future complete TPS_POLICY_ENGINE evaluation.
 @d3ka_role         POLICY/TEMPORAL
 @d3ka_links        Supplies A/authorization-policy enrichment adjacent to D3KA cells and
                    domain actions. Policy validity is Tv-scoped.
 @ai_role           AI may recommend or explain policy outcomes but cannot create/activate
                    authoritative policies autonomously.
 @security          Policy metadata is security/operation sensitive. Writes require governed
                    admin/migration authority and audit; runtime identities should be read-only.
 @performance       Small-to-moderate reference/configuration table; POLICY_KEY and active
                    domain/priority/time filtering are expected access patterns.
 @transaction       DDL implicit commit on deployment; runtime policy maintenance is caller-owned.
 @idempotency       CREATE TABLE non-idempotent; POLICY_KEY uniqueness supports stable identity.
 @failure_modes     Duplicate key, invalid lifecycle/time window, insufficient privilege.
                    A policy row existing in this table does NOT mean it is currently enforced;
                    enforcement requires policy-engine implementation/tests.
 @rollback_recovery Before policy use, controlled drop. Once policy history/actions depend on it,
                    preserve records and supersede/migrate rather than destructive deletion.
 @tests             Future policy-table unit/temporal tests; AI-003 exercises current policy
                    boundary indirectly through rights.
 @evidence          CORE-11 policy model/evaluation evidence and CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: CREATE TABLE, constraints,
                    TIMESTAMP WITH TIME ZONE.
 @links             docs/01-business/BUSINESS-RULES.md; docs/05-domain/RIGHTS-LICENSING.md;
                    src/10-policy/1010_tps_rule.sql; src/10-policy/1020_tps_policy_engine_pkg.pks
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one governed policy identity with temporal lifecycle and priority.
CREATE TABLE tps_policy (
    policy_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    policy_key           VARCHAR2(200) NOT NULL,
    -- Business/security/rights/operational policy namespace.
    policy_domain        VARCHAR2(100) NOT NULL,
    -- Lower/higher precedence semantics must be defined by evaluating engine before use;
    -- current table stores priority but current TPS_POLICY_ENGINE does not yet read it.
    priority             NUMBER DEFAULT 100 NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    valid_from           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to             TIMESTAMP WITH TIME ZONE,
    description          VARCHAR2(2000),
    CONSTRAINT uk_tps_policy_key UNIQUE(policy_key),
    CONSTRAINT ck_tps_policy_state CHECK(state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_tps_policy_validity CHECK(valid_to IS NULL OR valid_to > valid_from)
);
