-- TPSDBCORE01 | CORE-11 | R1 | NOT DEPLOYED
CREATE TABLE tps_policy (
    policy_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    policy_key           VARCHAR2(200) NOT NULL,
    policy_domain        VARCHAR2(100) NOT NULL,
    priority             NUMBER DEFAULT 100 NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    valid_from           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to             TIMESTAMP WITH TIME ZONE,
    description          VARCHAR2(2000),
    CONSTRAINT uk_tps_policy_key UNIQUE(policy_key),
    CONSTRAINT ck_tps_policy_state CHECK(state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETIRED')),
    CONSTRAINT ck_tps_policy_validity CHECK(valid_to IS NULL OR valid_to > valid_from)
);
