/*=============================================================================
 @file              src/10-policy/1010_tps_rule.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-11
 @workstream        WS-12 Policy/rules
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before rule data; R3_TRANSFORMATIVE after decision history exists
 @purpose           Persist ordered, typed rule definitions belonging to governed TPS_POLICY
                    records while allowing extensible deterministic rule payloads in JSON.
 @business_impact   Provides a central rule catalog for constraints such as rights, schedule,
                    commercial frequency, competitive conflict, content restrictions and
                    operational safety instead of embedding rules in front-end applications.
 @objects           Creates TPS_RULE with PK, unique rule key, policy FK and lifecycle check.
 @dependencies      TPS_POLICY.
 @upstream          Approved business/policy engineering and governed rule-authoring process.
 @downstream        Future complete TPS_POLICY_ENGINE evaluation, audit, certification.
 @d3ka_role         POLICY
 @d3ka_links        Encodes A/policy constraints that can authorize/reject actions derived from
                    D3KA knowledge/context. It is not itself an S/R/T cell.
 @ai_role           AI may explain/suggest candidate rules, but RULE_JSON and activation are
                    deterministic governed configuration and cannot be autonomously authored.
 @security          RULE_JSON can encode sensitive operational policy. Writes restricted and
                    audited; no secrets/credentials are permitted in JSON payloads.
 @performance       Expected moderate reference/configuration volume. POLICY_ID,
                    EVALUATION_ORDER and STATE are dominant future evaluation paths; indexes
                    must be designed after engine query shape is finalized and measured.
 @transaction       DDL implicit commit on deployment; rule maintenance is caller transaction.
 @idempotency       CREATE TABLE non-idempotent; RULE_KEY uniqueness provides stable rule identity.
 @failure_modes     Missing policy, duplicate key, invalid state/JSON, or rule semantics not
                    understood by evaluator. Current v0.02 policy engine does NOT evaluate
                    TPS_RULE yet; existence of rows must not be represented as enforcement.
 @rollback_recovery Before use, controlled drop. After decisions rely on rules, preserve/supersede
                    history and migrate rather than delete authoritative decision definitions.
 @tests             Future rule-parser/evaluator/unit/order/conflict tests are mandatory before
                    TPS_RULE can be treated as enforced policy.
 @evidence          CORE-11 rule evaluation evidence and CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: JSON, CREATE TABLE, constraints.
 @links             src/10-policy/1000_tps_policy.sql;
                    src/10-policy/1020_tps_policy_engine_pkg.pks;
                    docs/01-business/BUSINESS-RULES.md;
                    docs/09-security/SECURITY-ARCHITECTURE-MASTER-v0.02.md
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one governed deterministic rule definition associated with one policy.
CREATE TABLE tps_rule (
    rule_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    policy_id            NUMBER NOT NULL,
    rule_key             VARCHAR2(200) NOT NULL,
    -- Declares evaluator family/type; vocabulary must be governed before execution.
    rule_type            VARCHAR2(50) NOT NULL,
    -- Ordering metadata for a future evaluator. Current engine does not yet consume it.
    evaluation_order     NUMBER DEFAULT 100 NOT NULL,
    -- Extensible deterministic rule definition; schema/validation contract is still required.
    rule_json            JSON NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_rule_key UNIQUE(rule_key),
    CONSTRAINT fk_tps_rule_policy FOREIGN KEY(policy_id) REFERENCES tps_policy(policy_id),
    CONSTRAINT ck_tps_rule_state CHECK(state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETIRED'))
);
