-- TPSDBCORE01 | CORE-11 | R1 | NOT DEPLOYED
CREATE TABLE tps_rule (
    rule_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    policy_id            NUMBER NOT NULL,
    rule_key             VARCHAR2(200) NOT NULL,
    rule_type            VARCHAR2(50) NOT NULL,
    evaluation_order     NUMBER DEFAULT 100 NOT NULL,
    rule_json            JSON NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_rule_key UNIQUE(rule_key),
    CONSTRAINT fk_tps_rule_policy FOREIGN KEY(policy_id) REFERENCES tps_policy(policy_id),
    CONSTRAINT ck_tps_rule_state CHECK(state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETIRED'))
);
