-- TPSDBCORE01 | CORE-09 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_assertion (
    assertion_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subject_entity_id    NUMBER NOT NULL,
    predicate_type_id    NUMBER NOT NULL,
    object_entity_id     NUMBER,
    literal_value        JSON,
    source_id            NUMBER NOT NULL,
    confidence           NUMBER(5,4),
    assertion_class      VARCHAR2(30) NOT NULL,
    verification_status  VARCHAR2(30) DEFAULT 'UNVERIFIED' NOT NULL,
    verified_by_entity_id NUMBER,
    verified_at          TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_assertion_subject FOREIGN KEY (subject_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_assertion_predicate FOREIGN KEY (predicate_type_id) REFERENCES tps_relation_type(relation_type_id),
    CONSTRAINT fk_tps_assertion_object FOREIGN KEY (object_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_assertion_source FOREIGN KEY (source_id) REFERENCES tps_source(source_id),
    CONSTRAINT fk_tps_assertion_verifier FOREIGN KEY (verified_by_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_assertion_value CHECK ((object_entity_id IS NOT NULL AND literal_value IS NULL) OR (object_entity_id IS NULL AND literal_value IS NOT NULL)),
    CONSTRAINT ck_tps_assertion_conf CHECK (confidence IS NULL OR (confidence >=0 AND confidence <=1)),
    CONSTRAINT ck_tps_assertion_class CHECK (assertion_class IN ('FACT','OBSERVATION','INFERENCE','AI_INFERENCE','HUMAN_ASSERTION','EXTERNAL_IMPORT')),
    CONSTRAINT ck_tps_assertion_verify CHECK (verification_status IN ('UNVERIFIED','VERIFIED','DISPUTED','REJECTED','SUPERSEDED'))
);
