/*=============================================================================
 @file              src/08-knowledge/810_tps_assertion.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-09/16
 @workstream        WS-10 Knowledge assertions / WS-11 AI validation
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before assertion data; R3_TRANSFORMATIVE after knowledge/audit use
 @purpose           Persist explicit subject-predicate-object-or-literal assertions with mandatory
                    provenance, confidence, assertion class and verification state so inferred/imported/
                    AI-generated knowledge never silently becomes an unqualified fact.
 @business_impact   Creates an auditable knowledge layer for journalism, rights, metadata enrichment,
                    entity resolution and AI reasoning, separating evidence/claims from authoritative action.
 @objects           Creates TPS_ASSERTION with PK/FKs, XOR value constraint, confidence/class/verification checks.
 @dependencies      TPS_ENTITY, TPS_RELATION_TYPE, TPS_SOURCE.
 @upstream          Human assertions, observations, imports, inference pipelines and AI reasoning outputs.
 @downstream        Knowledge graph enrichment, verification workflows, Graph RAG grounding, AI decision evidence.
 @d3ka_role         PROVENANCE/KNOWLEDGE/RELATION
 @d3ka_links        SUBJECT_ENTITY_ID + PREDICATE_TYPE_ID + OBJECT_ENTITY_ID mirrors S/R/T for claim semantics;
                    literal assertions allow a predicate value without fabricating a target entity. SOURCE_ID=E,
                    CONFIDENCE/VERIFICATION=Q. Assertions are not automatically TPS_RELATION cells.
 @ai_role           AI_INFERENCE is explicit. AI output should begin UNVERIFIED unless separately verified;
                    verified status/human verifier establishes governance trace. AI assertion != operational authority.
 @security          Assertions may encode disputed/sensitive claims. Mandatory source and verification metadata
                    support accountability. Direct writes/reviews require role separation and audit.
 @performance       Potential high knowledge volume. Common paths: subject, predicate, object, source,
                    verification status/class. Index strategy is not yet defined here and needs workload evidence.
 @transaction       DDL implicit commit; runtime assertion/verification updates caller-owned and audited.
 @idempotency       CREATE TABLE non-idempotent. Current DDL has no natural duplicate-assertion uniqueness rule;
                    ingest/reasoning pipeline must prevent accidental duplicate claims until policy is formalized.
 @failure_modes     XOR constraint requires either object entity OR literal JSON, never both/neither; invalid
                    confidence/class/status or missing FKs fail. Verification consistency is not fully constrained:
                    current DDL allows VERIFIED without VERIFIED_BY/VERIFIED_AT and vice versa; validation/package
                    rules are required before CORE-09 certification.
 @rollback_recovery Before use controlled drop. After claims/evidence exist, preserve/retract/supersede history;
                    destructive deletion is exceptional because provenance/AI audit may depend on assertions.
 @tests             tests/AI/AI-001_authority_classes.sql; AI-002_inference_verification.sql;
                    AI-004_graph_rag_evidence.sql; dedicated assertion constraint/verification tests pending.
 @evidence          CORE-09 assertion/provenance evidence; CORE-16 AI grounding/verification; CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: JSON, constraints, temporal datatypes.
 @links             src/02-kernel/230_tps_source.sql; src/03-d3ka/300_tps_relation_type.sql;
                    docs/07-ai-ml/AI-ML-RAG-AGENTS-MASTER-SPEC-v0.02.md;
                    docs/06-data-dictionary/AI-DICTIONARY.md
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full documentation and verification-limit note; DDL unchanged.
=============================================================================*/

-- One row = one provenance-bearing claim about an entity, not automatically an authoritative fact.
CREATE TABLE tps_assertion (
    assertion_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subject_entity_id    NUMBER NOT NULL,
    -- Uses governed relation ontology as assertion predicate vocabulary.
    predicate_type_id    NUMBER NOT NULL,
    -- Exactly one of OBJECT_ENTITY_ID or LITERAL_VALUE must be present.
    object_entity_id     NUMBER,
    literal_value        JSON,
    -- Provenance is mandatory for every assertion, including AI inference.
    source_id            NUMBER NOT NULL,
    confidence           NUMBER(5,4),
    assertion_class      VARCHAR2(30) NOT NULL,
    verification_status  VARCHAR2(30) DEFAULT 'UNVERIFIED' NOT NULL,
    verified_by_entity_id NUMBER,
    verified_at          TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_assertion_subject FOREIGN KEY (subject_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_assertion_predicate FOREIGN KEY (predicate_type_id) REFERENCES tps_relation_type(relation_type_id),
    CONSTRAINT fk_tps_assertion_object FOREIGN KEY (object_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_assertion_source FOREIGN KEY (source_id) REFERENCES tps_source(source_id),
    CONSTRAINT fk_tps_assertion_verifier FOREIGN KEY (verified_by_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT ck_tps_assertion_value CHECK ((object_entity_id IS NOT NULL AND literal_value IS NULL) OR (object_entity_id IS NULL AND literal_value IS NOT NULL)),
    CONSTRAINT ck_tps_assertion_conf CHECK (confidence IS NULL OR (confidence >=0 AND confidence <=1)),
    CONSTRAINT ck_tps_assertion_class CHECK (assertion_class IN ('FACT','OBSERVATION','INFERENCE','AI_INFERENCE','HUMAN_ASSERTION','EXTERNAL_IMPORT')),
    CONSTRAINT ck_tps_assertion_verify CHECK (verification_status IN ('UNVERIFIED','VERIFIED','DISPUTED','REJECTED','SUPERSEDED'))
);
