-- TPSDBCORE01 | COMMERCIAL DOMAIN | R1 | NOT DEPLOYED
CREATE TABLE tps_placement (
    placement_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    campaign_entity_id    NUMBER NOT NULL,
    creative_entity_id    NUMBER NOT NULL,
    channel_entity_id     NUMBER NOT NULL,
    schedule_item_id      NUMBER,
    context_id            NUMBER,
    planned_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    played_event_id       NUMBER,
    state                 VARCHAR2(30) DEFAULT 'PLANNED' NOT NULL,
    decision_json         JSON,
    CONSTRAINT fk_tps_placement_campaign FOREIGN KEY(campaign_entity_id) REFERENCES tps_campaign(campaign_entity_id),
    CONSTRAINT fk_tps_placement_creative FOREIGN KEY(creative_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_placement_channel FOREIGN KEY(channel_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_placement_scheditem FOREIGN KEY(schedule_item_id) REFERENCES tps_schedule_item(schedule_item_id),
    CONSTRAINT fk_tps_placement_context FOREIGN KEY(context_id) REFERENCES tps_context(context_id),
    CONSTRAINT fk_tps_placement_event FOREIGN KEY(played_event_id) REFERENCES tps_event(event_id),
    CONSTRAINT ck_tps_placement_state CHECK(state IN ('PLANNED','AUTHORIZED','REJECTED','PLAYED','CANCELLED','MISSED'))
);
