-- TPSDBCORE01 | CORE-12 | R1 | NOT DEPLOYED
CREATE TABLE tps_audit_event (
    audit_event_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_time           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    actor                VARCHAR2(200) NOT NULL,
    actor_role           VARCHAR2(200),
    action_code          VARCHAR2(120) NOT NULL,
    object_class         VARCHAR2(100),
    object_key           VARCHAR2(500),
    correlation_id       VARCHAR2(200),
    change_id            VARCHAR2(200),
    outcome              VARCHAR2(30) NOT NULL,
    details_json         JSON,
    CONSTRAINT ck_tps_audit_outcome CHECK(outcome IN ('SUCCESS','DENIED','FAILED','CANCELLED'))
);
CREATE INDEX ix_tps_audit_time ON tps_audit_event(event_time);
CREATE INDEX ix_tps_audit_corr ON tps_audit_event(correlation_id);
