-- COMP-000 — Canonical kernel compile/object gate
-- READ ONLY. Expected final output: COMP-000=PASS
SET SERVEROUTPUT ON
DECLARE
  l_missing NUMBER;
  l_invalid NUMBER;
  l_errors  NUMBER;
  l_entity_types NUMBER;
  l_relation_types NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_missing
  FROM (
    SELECT 'TPS_SCHEMA_MIGRATION' n,'TABLE' t FROM dual UNION ALL
    SELECT 'TPS_ENTITY_TYPE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_ENTITY','TABLE' FROM dual UNION ALL
    SELECT 'TPS_PROPERTY','TABLE' FROM dual UNION ALL
    SELECT 'TPS_SOURCE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_CONTEXT_TYPE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_CONTEXT','TABLE' FROM dual UNION ALL
    SELECT 'TPS_RELATION_TYPE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_RELATION','TABLE' FROM dual UNION ALL
    SELECT 'TPS_FACT_CLASS','TABLE' FROM dual UNION ALL
    SELECT 'TPS_FACT_CLASS_MAPPING','TABLE' FROM dual UNION ALL
    SELECT 'TPS_VECTOR_TYPE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_VECTOR','TABLE' FROM dual UNION ALL
    SELECT 'TPS_ASSERTION','TABLE' FROM dual UNION ALL
    SELECT 'TPS_EVENT_TYPE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_EVENT','TABLE' FROM dual UNION ALL
    SELECT 'TPS_POLICY','TABLE' FROM dual UNION ALL
    SELECT 'TPS_RULE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_AI_MODEL','TABLE' FROM dual UNION ALL
    SELECT 'TPS_AI_AGENT','TABLE' FROM dual UNION ALL
    SELECT 'TPS_AI_TOOL','TABLE' FROM dual UNION ALL
    SELECT 'TPS_AI_DECISION','TABLE' FROM dual UNION ALL
    SELECT 'TPS_AUDIT_EVENT','TABLE' FROM dual UNION ALL
    SELECT 'TPS_STATION','TABLE' FROM dual UNION ALL
    SELECT 'TPS_CHANNEL','TABLE' FROM dual UNION ALL
    SELECT 'TPS_PROGRAM','TABLE' FROM dual UNION ALL
    SELECT 'TPS_SCHEDULE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_SCHEDULE_ITEM','TABLE' FROM dual UNION ALL
    SELECT 'TPS_MEDIA_ASSET','TABLE' FROM dual UNION ALL
    SELECT 'TPS_CAMPAIGN','TABLE' FROM dual UNION ALL
    SELECT 'TPS_PLACEMENT','TABLE' FROM dual UNION ALL
    SELECT 'TPS_RIGHT_GRANT','TABLE' FROM dual UNION ALL
    SELECT 'TPS_AUDIENCE_SEGMENT','TABLE' FROM dual UNION ALL
    SELECT 'TPS_AUDIENCE_OBSERVATION','TABLE' FROM dual UNION ALL
    SELECT 'TPS_EDITORIAL_ITEM','TABLE' FROM dual UNION ALL
    SELECT 'TPS_D3KA_PKG','PACKAGE' FROM dual UNION ALL
    SELECT 'TPS_D3KA_PKG','PACKAGE BODY' FROM dual UNION ALL
    SELECT 'TPS_RIGHTS_PKG','PACKAGE' FROM dual UNION ALL
    SELECT 'TPS_RIGHTS_PKG','PACKAGE BODY' FROM dual UNION ALL
    SELECT 'TPS_POLICY_ENGINE_PKG','PACKAGE' FROM dual UNION ALL
    SELECT 'TPS_POLICY_ENGINE_PKG','PACKAGE BODY' FROM dual
  ) e
  WHERE NOT EXISTS (
    SELECT 1 FROM user_objects u
     WHERE u.object_name=e.n AND u.object_type=e.t
  );

  SELECT COUNT(*) INTO l_invalid
    FROM user_objects
   WHERE object_name LIKE 'TPS\_%' ESCAPE '\'
     AND object_type IN ('PACKAGE','PACKAGE BODY','VIEW','TRIGGER')
     AND status <> 'VALID';

  SELECT COUNT(*) INTO l_errors
    FROM user_errors
   WHERE name LIKE 'TPS\_%' ESCAPE '\';

  SELECT COUNT(*) INTO l_entity_types FROM tps_entity_type WHERE lifecycle_state='ACTIVE';
  SELECT COUNT(*) INTO l_relation_types FROM tps_relation_type WHERE lifecycle_state='ACTIVE';

  DBMS_OUTPUT.PUT_LINE('COMP000_MISSING='||l_missing);
  DBMS_OUTPUT.PUT_LINE('COMP000_INVALID='||l_invalid);
  DBMS_OUTPUT.PUT_LINE('COMP000_USER_ERRORS='||l_errors);
  DBMS_OUTPUT.PUT_LINE('COMP000_ACTIVE_ENTITY_TYPES='||l_entity_types);
  DBMS_OUTPUT.PUT_LINE('COMP000_ACTIVE_RELATION_TYPES='||l_relation_types);

  IF l_missing<>0 OR l_invalid<>0 OR l_errors<>0 OR l_entity_types=0 OR l_relation_types=0 THEN
    RAISE_APPLICATION_ERROR(-20900,'COMP-000=FAIL');
  END IF;

  DBMS_OUTPUT.PUT_LINE('COMP-000=PASS');
END;
/
