-- TPSDBCORE01 | RIGHTS DOMAIN | R1 | NOT DEPLOYED
CREATE TABLE tps_right_grant (
    right_grant_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    content_entity_id     NUMBER NOT NULL,
    rights_holder_entity_id NUMBER,
    beneficiary_entity_id NUMBER NOT NULL,
    action_code           VARCHAR2(100) NOT NULL,
    territory_entity_id   NUMBER,
    context_id            NUMBER,
    valid_from            TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_to              TIMESTAMP WITH TIME ZONE NOT NULL,
    decision              VARCHAR2(10) NOT NULL,
    source_id             NUMBER NOT NULL,
    restrictions_json     JSON,
    state                 VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT fk_tps_right_content FOREIGN KEY(content_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_right_holder FOREIGN KEY(rights_holder_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_right_beneficiary FOREIGN KEY(beneficiary_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_right_territory FOREIGN KEY(territory_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_right_context FOREIGN KEY(context_id) REFERENCES tps_context(context_id),
    CONSTRAINT fk_tps_right_source FOREIGN KEY(source_id) REFERENCES tps_source(source_id),
    CONSTRAINT ck_tps_right_time CHECK(valid_to > valid_from),
    CONSTRAINT ck_tps_right_decision CHECK(decision IN ('ALLOW','DENY')),
    CONSTRAINT ck_tps_right_state CHECK(state IN ('ACTIVE','SUPERSEDED','REVOKED','EXPIRED'))
);
CREATE INDEX ix_tps_right_lookup ON tps_right_grant(content_entity_id,beneficiary_entity_id,action_code,valid_from,valid_to,state);
