-- TPSDBCORE01 | CORE-04 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_relation_type (
    relation_type_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    relation_code            VARCHAR2(120) NOT NULL,
    display_name             VARCHAR2(200) NOT NULL,
    inverse_relation_code    VARCHAR2(120),
    source_entity_type_id    NUMBER,
    target_entity_type_id    NUMBER,
    allow_self               NUMBER(1) DEFAULT 0 NOT NULL,
    requires_context         NUMBER(1) DEFAULT 0 NOT NULL,
    requires_provenance      NUMBER(1) DEFAULT 0 NOT NULL,
    policy_sensitive         NUMBER(1) DEFAULT 0 NOT NULL,
    lifecycle_state          VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    description              VARCHAR2(1000),
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_relation_type_code UNIQUE (relation_code),
    CONSTRAINT fk_tps_reltype_source_type FOREIGN KEY (source_entity_type_id) REFERENCES tps_entity_type(entity_type_id),
    CONSTRAINT fk_tps_reltype_target_type FOREIGN KEY (target_entity_type_id) REFERENCES tps_entity_type(entity_type_id),
    CONSTRAINT ck_tps_reltype_bool1 CHECK (allow_self IN (0,1)),
    CONSTRAINT ck_tps_reltype_bool2 CHECK (requires_context IN (0,1)),
    CONSTRAINT ck_tps_reltype_bool3 CHECK (requires_provenance IN (0,1)),
    CONSTRAINT ck_tps_reltype_bool4 CHECK (policy_sensitive IN (0,1)),
    CONSTRAINT ck_tps_reltype_state CHECK (lifecycle_state IN ('ACTIVE','INACTIVE','DEPRECATED','RETIRED'))
);
