/*=============================================================================
 @file              src/03-d3ka/300_tps_relation_type.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-04
 @workstream        WS-05 D3KA relation kernel
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before use; R3_TRANSFORMATIVE after relations exist
 @purpose           Define the governed ontology of admissible D3KA R-axis relation
                    types, including optional source/target type constraints and
                    requirements for context, provenance and policy validation.
 @business_impact   Converts business semantics such as OWNS, BROADCASTS, PRESENTS,
                    PLAYED_ON, TARGETS and LICENSED_BY into controlled reusable
                    relationship types instead of application-specific foreign-key logic.
 @objects           Creates TPS_RELATION_TYPE with PK/UK/FKs/check constraints.
 @dependencies      TPS_ENTITY_TYPE.
 @upstream          RELATION-DICTIONARY, business rules, domain architecture and ADRs.
 @downstream        TPS_RELATION, TPS_D3KA_PKG, Property Graph edge semantics,
                    policy engine, D3KA coverage and all relation-oriented APIs/AI retrieval.
 @d3ka_role         RELATION
 @d3ka_links        This table defines the R axis. SOURCE_ENTITY_TYPE_ID and
                    TARGET_ENTITY_TYPE_ID constrain which entity classes may occupy
                    the S and T positions for a given R value.
 @ai_role           AI may propose relationship candidates but cannot redefine ontology
                    or bypass REQUIRES_CONTEXT/REQUIRES_PROVENANCE/POLICY_SENSITIVE rules.
 @security          POLICY_SENSITIVE marks relationship classes that require additional
                    deterministic authorization. Ontology writes are restricted governance
                    operations because a type change can alter system-wide semantics.
 @performance       Small governed reference table. RELATION_CODE unique lookup is the
                    dominant D3KA write path; PK/type-FK lookups support validation.
 @transaction       DDL implicit commit on deployment. Runtime relation creation uses
                    this table read-only through TPS_D3KA_PKG.
 @idempotency       CREATE TABLE is not idempotent. RELATION_CODE uniqueness supports
                    idempotent reference-data loading under controlled migration.
 @failure_modes     Missing TPS_ENTITY_TYPE, duplicate relation code, invalid boolean/
                    lifecycle value, insufficient privilege. Dependent D3KA deployment
                    must stop on any ontology failure.
 @rollback_recovery Before relation data exists, controlled DROP is possible. Once used,
                    relation-type identifiers are semantic history and must be preserved/
                    migrated; destructive renumbering/deletion is prohibited.
 @tests             tests/D3KA/D3KA-002_reject_self.sql;
                    D3KA-003_require_context.sql; D3KA-004_require_provenance.sql;
                    relation constraint/coverage suites.
 @evidence          CORE-04 relation-kernel evidence; CORE-15 D3KA/graph validation;
                    CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: CREATE TABLE and
                    constraints; Oracle Property Graph documentation for edge semantics.
 @links             docs/06-data-dictionary/RELATION-DICTIONARY.md;
                    docs/04-d3ka/D3KA-ENGINEERING-SPEC-v0.02.md;
                    src/02-kernel/200_tps_entity_type.sql;
                    src/03-d3ka/310_tps_relation.sql;
                    src/03-d3ka/320_tps_d3ka_pkg.pks
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one governed semantic relation type for the D3KA R axis.
CREATE TABLE tps_relation_type (
    relation_type_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    -- Stable machine-readable predicate key, e.g. BROADCASTS or LICENSED_BY.
    relation_code            VARCHAR2(120) NOT NULL,
    display_name             VARCHAR2(200) NOT NULL,
    -- Optional semantic inverse metadata; not an instruction to duplicate edges.
    inverse_relation_code    VARCHAR2(120),
    -- Optional S/T entity-type restrictions checked by TPS_D3KA_PKG.
    source_entity_type_id    NUMBER,
    target_entity_type_id    NUMBER,
    -- 0 = S and T may not be the same entity; 1 = self-relation is permitted.
    allow_self               NUMBER(1) DEFAULT 0 NOT NULL,
    -- These flags define mandatory orthogonal dimensions of a valid D3KA cell.
    requires_context         NUMBER(1) DEFAULT 0 NOT NULL,
    requires_provenance      NUMBER(1) DEFAULT 0 NOT NULL,
    policy_sensitive         NUMBER(1) DEFAULT 0 NOT NULL,
    lifecycle_state          VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    description              VARCHAR2(1000),
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_relation_type_code UNIQUE (relation_code),
    CONSTRAINT fk_tps_reltype_source_type FOREIGN KEY (source_entity_type_id) REFERENCES tps_entity_type(entity_type_id),
    CONSTRAINT fk_tps_reltype_target_type FOREIGN KEY (target_entity_type_id) REFERENCES tps_entity_type(entity_type_id),
    CONSTRAINT ck_tps_reltype_bool1 CHECK (allow_self IN (0,1)),
    CONSTRAINT ck_tps_reltype_bool2 CHECK (requires_context IN (0,1)),
    CONSTRAINT ck_tps_reltype_bool3 CHECK (requires_provenance IN (0,1)),
    CONSTRAINT ck_tps_reltype_bool4 CHECK (policy_sensitive IN (0,1)),
    CONSTRAINT ck_tps_reltype_state CHECK (lifecycle_state IN ('ACTIVE','INACTIVE','DEPRECATED','RETIRED'))
);
