-- TPSDBCORE01 | CORE-04 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_relation (
    relation_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    source_entity_id         NUMBER NOT NULL,
    relation_type_id         NUMBER NOT NULL,
    target_entity_id         NUMBER NOT NULL,
    context_id               NUMBER,
    provenance_source_id     NUMBER,
    weight                   NUMBER,
    confidence               NUMBER(5,4),
    state                    VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    assertion_class          VARCHAR2(30) DEFAULT 'FACT' NOT NULL,
    attributes_json          JSON,
    valid_from               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to                 TIMESTAMP WITH TIME ZONE,
    observed_at              TIMESTAMP WITH TIME ZONE,
    recorded_at              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    created_by               VARCHAR2(128) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
    CONSTRAINT fk_tps_relation_source FOREIGN KEY (source_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_relation_type FOREIGN KEY (relation_type_id) REFERENCES tps_relation_type(relation_type_id),
    CONSTRAINT fk_tps_relation_target FOREIGN KEY (target_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_relation_context FOREIGN KEY (context_id) REFERENCES tps_context(context_id),
    CONSTRAINT fk_tps_relation_prov FOREIGN KEY (provenance_source_id) REFERENCES tps_source(source_id),
    CONSTRAINT ck_tps_relation_state CHECK (state IN ('ACTIVE','INACTIVE','SUPERSEDED','RETRACTED')),
    CONSTRAINT ck_tps_relation_assertion CHECK (assertion_class IN ('FACT','OBSERVATION','INFERENCE','AI_INFERENCE','HUMAN_ASSERTION','EXTERNAL_IMPORT')),
    CONSTRAINT ck_tps_relation_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT ck_tps_relation_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);

-- Function-based uniqueness: only current ACTIVE cells participate. Historical rows
-- evaluate to all-NULL keys and therefore remain repeatable/preservable.
CREATE UNIQUE INDEX ux_tps_relation_active_cell
ON tps_relation (
    CASE WHEN state='ACTIVE' AND valid_to IS NULL THEN source_entity_id END,
    CASE WHEN state='ACTIVE' AND valid_to IS NULL THEN relation_type_id END,
    CASE WHEN state='ACTIVE' AND valid_to IS NULL THEN target_entity_id END,
    CASE WHEN state='ACTIVE' AND valid_to IS NULL THEN NVL(context_id,0) END
);
