/*=============================================================================
 @file              src/03-d3ka/350_tps_fact_class.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-15
 @workstream        WS-19 Validation / D3KA semantic coverage
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before coverage catalog data; R3 after certification history depends on IDs
 @purpose           Define the governed universe of business fact classes used as the denominator
                    for measuring how much approved business knowledge is representable through D3KA.
 @business_impact   Converts the project requirement "at least 90% D3KA/graph semantic coverage"
                    from narrative into measurable catalog data by business domain and weight.
 @objects           Creates TPS_FACT_CLASS with identity, unique key, eligibility/mandatory flags,
                    weight and lifecycle constraints.
 @dependencies      None.
 @upstream          Business analysis, domain maps, requirements and approved knowledge catalog.
 @downstream        TPS_FACT_CLASS_MAPPING, TPS_D3KA_COVERAGE_V, D3KA coverage tests/certification.
 @d3ka_role         D3KA COVERAGE GOVERNANCE
 @d3ka_links        Each eligible fact class represents one class of business knowledge that
                    must be mapped to D3KA_RELATION or another explicitly justified representation.
 @ai_role           AI may assist discovery/classification of missing fact classes but cannot
                    alter eligibility/mandatory/weight values without governed review.
 @security          Governance metadata; writes restricted to architecture/certification authority.
 @performance       Small reference/catalog table. FACT_CLASS_KEY unique lookup and DOMAIN_CODE grouping.
 @transaction       DDL implicit commit on deployment; catalog maintenance caller-owned.
 @idempotency       CREATE TABLE non-idempotent; FACT_CLASS_KEY is stable natural identity.
 @failure_modes     Missing business fact classes bias the denominator and can falsely inflate coverage.
                    WEIGHT exists but current TPS_D3KA_COVERAGE_V v0.02 does not use it; weighted
                    and per-domain certification is therefore still incomplete.
 @rollback_recovery Before use controlled drop; after certification history exists preserve IDs and migrate.
 @tests             tests/D3KA/D3KA-011_coverage.sql plus future weighted/per-domain coverage tests.
 @evidence          CORE-15 coverage evidence and CORE-20 certification.
 @references        Project D3KA engineering specification; Oracle CREATE TABLE/constraint documentation.
 @links             docs/04-d3ka/D3KA-ENGINEERING-SPEC-v0.02.md;
                    src/03-d3ka/351_tps_fact_class_mapping.sql;
                    src/03-d3ka/360_d3ka_coverage_v.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one governed business-knowledge/fact class in the D3KA coverage denominator.
CREATE TABLE tps_fact_class (
    fact_class_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fact_class_key        VARCHAR2(200) NOT NULL,
    -- Business/domain partition used for future per-domain coverage certification.
    domain_code           VARCHAR2(100) NOT NULL,
    description           VARCHAR2(1000) NOT NULL,
    -- 1 means this knowledge class is expected to be meaningfully representable through D3KA.
    d3ka_eligible         NUMBER(1) DEFAULT 1 NOT NULL,
    mandatory_for_v1      NUMBER(1) DEFAULT 1 NOT NULL,
    -- Relative business importance intended for weighted coverage calculations.
    weight                NUMBER DEFAULT 1 NOT NULL,
    lifecycle_state       VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT uk_tps_fact_class_key UNIQUE(fact_class_key),
    CONSTRAINT ck_tps_fact_class_bool1 CHECK(d3ka_eligible IN (0,1)),
    CONSTRAINT ck_tps_fact_class_bool2 CHECK(mandatory_for_v1 IN (0,1)),
    CONSTRAINT ck_tps_fact_class_state CHECK(lifecycle_state IN ('ACTIVE','DEPRECATED','RETIRED'))
);
