-- TPSDBCORE01 | CORE-15 | R1 | NOT DEPLOYED
CREATE TABLE tps_fact_class (
    fact_class_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fact_class_key        VARCHAR2(200) NOT NULL,
    domain_code           VARCHAR2(100) NOT NULL,
    description           VARCHAR2(1000) NOT NULL,
    d3ka_eligible         NUMBER(1) DEFAULT 1 NOT NULL,
    mandatory_for_v1      NUMBER(1) DEFAULT 1 NOT NULL,
    weight                NUMBER DEFAULT 1 NOT NULL,
    lifecycle_state       VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT uk_tps_fact_class_key UNIQUE(fact_class_key),
    CONSTRAINT ck_tps_fact_class_bool1 CHECK(d3ka_eligible IN (0,1)),
    CONSTRAINT ck_tps_fact_class_bool2 CHECK(mandatory_for_v1 IN (0,1)),
    CONSTRAINT ck_tps_fact_class_state CHECK(lifecycle_state IN ('ACTIVE','DEPRECATED','RETIRED'))
);
