/*=============================================================================
 @file              src/03-d3ka/351_tps_fact_class_mapping.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-15
 @workstream        WS-19 D3KA semantic coverage validation
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before catalog use; R3 after certification evidence depends on mapping IDs
 @purpose           Map each governed business fact class to its intended physical/logical
                    representation and implementation status, including optional D3KA relation type.
 @business_impact   Makes architectural coverage explicit and auditable: a fact class cannot
                    be silently counted as D3KA coverage unless it is mapped and implemented/
                    validated/certified under the defined representation class.
 @objects           Creates TPS_FACT_CLASS_MAPPING with FKs and representation/status checks.
 @dependencies      TPS_FACT_CLASS and TPS_RELATION_TYPE.
 @upstream          Fact catalog, relation ontology and implementation/certification decisions.
 @downstream        TPS_D3KA_COVERAGE_V, traceability reports and CORE-15 certification.
 @d3ka_role         D3KA COVERAGE MAPPING
 @d3ka_links        For REPRESENTATION_CLASS='D3KA_RELATION', RELATION_TYPE_ID links the business
                    fact class to the governed R-axis predicate implementing it.
 @ai_role           AI may identify candidate missing mappings but cannot promote status to
                    IMPLEMENTED/VALIDATED/CERTIFIED without source/tests/evidence.
 @security          Engineering governance metadata; write access restricted.
 @performance       Small mapping table. FACT_CLASS_ID and REPRESENTATION_CLASS are common coverage paths.
 @transaction       DDL implicit commit; mapping maintenance caller transaction.
 @idempotency       CREATE TABLE non-idempotent. This source currently defines no unique constraint
                    preventing duplicate mappings for one fact/representation/relation tuple; data-loading
                    rules/tests must prevent ambiguous duplicates until a deliberate uniqueness rule is approved.
 @failure_modes     Incorrect status can overstate maturity. Mapping a fact class as D3KA_RELATION without
                    a relation type is structurally allowed by current DDL, so certification must validate
                    semantic completeness rather than rely solely on FK constraints.
 @rollback_recovery Preserve historical mapping/evidence once used for certification; migrate/supersede.
 @tests             tests/D3KA/D3KA-011_coverage.sql and future mapping-integrity/duplicate tests.
 @evidence          CORE-15 mapping/coverage traceability; CORE-20 release evidence.
 @references        Project D3KA engineering specification; Oracle SQL constraints documentation.
 @links             src/03-d3ka/350_tps_fact_class.sql;
                    src/03-d3ka/300_tps_relation_type.sql;
                    src/03-d3ka/360_d3ka_coverage_v.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one declared implementation mapping for a governed fact class.
CREATE TABLE tps_fact_class_mapping (
    fact_class_mapping_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fact_class_id         NUMBER NOT NULL,
    -- Required semantically for D3KA_RELATION mappings, though current DDL permits NULL.
    relation_type_id      NUMBER,
    representation_class  VARCHAR2(30) NOT NULL,
    -- Status is engineering maturity, not runtime data state.
    implementation_status VARCHAR2(30) DEFAULT 'DESIGNED' NOT NULL,
    -- Repository/object/test/evidence locator for human traceability.
    implementation_ref    VARCHAR2(1000),
    CONSTRAINT fk_tps_factmap_fact FOREIGN KEY(fact_class_id) REFERENCES tps_fact_class(fact_class_id),
    CONSTRAINT fk_tps_factmap_reltype FOREIGN KEY(relation_type_id) REFERENCES tps_relation_type(relation_type_id),
    CONSTRAINT ck_tps_factmap_repr CHECK(representation_class IN ('D3KA_RELATION','ENTITY_PROPERTY','EVENT','LEDGER','VECTOR','OTHER')),
    CONSTRAINT ck_tps_factmap_status CHECK(implementation_status IN ('DESIGNED','IMPLEMENTED','VALIDATED','CERTIFIED','BLOCKED'))
);
