-- TPSDBCORE01 | CORE-15 | R1 | NOT DEPLOYED
CREATE TABLE tps_fact_class_mapping (
    fact_class_mapping_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fact_class_id         NUMBER NOT NULL,
    relation_type_id      NUMBER,
    representation_class  VARCHAR2(30) NOT NULL,
    implementation_status VARCHAR2(30) DEFAULT 'DESIGNED' NOT NULL,
    implementation_ref    VARCHAR2(1000),
    CONSTRAINT fk_tps_factmap_fact FOREIGN KEY(fact_class_id) REFERENCES tps_fact_class(fact_class_id),
    CONSTRAINT fk_tps_factmap_reltype FOREIGN KEY(relation_type_id) REFERENCES tps_relation_type(relation_type_id),
    CONSTRAINT ck_tps_factmap_repr CHECK(representation_class IN ('D3KA_RELATION','ENTITY_PROPERTY','EVENT','LEDGER','VECTOR','OTHER')),
    CONSTRAINT ck_tps_factmap_status CHECK(implementation_status IN ('DESIGNED','IMPLEMENTED','VALIDATED','CERTIFIED','BLOCKED'))
);
