-- V0001 PRE-DATA ROLLBACK
-- AUTHORIZED ONLY before business data/use and before V0002+.
-- Captured evidence must be retained before execution.
SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE

DROP VIEW tps_station_now_programming_v;
DROP VIEW tps_entity_api_v;
DROP VIEW tps_graph_neighbors_v;
DROP PROPERTY GRAPH tps_media_knowledge_graph;
DROP VIEW tps_d3ka_coverage_v;
DROP VIEW tps_d3ka_invariant_violations_v;
DROP VIEW tps_d3ka_history_v;
DROP VIEW tps_d3ka_active_v;

DROP PACKAGE tps_policy_engine_pkg;
DROP PACKAGE tps_rights_pkg;
DROP PACKAGE tps_d3ka_pkg;

DROP TABLE tps_editorial_item CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_audience_observation CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_audience_segment CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_right_grant CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_placement CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_campaign CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_media_asset CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_schedule_item CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_schedule CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_program CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_channel CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_station CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_audit_event CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_ai_decision CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_ai_agent CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_ai_tool CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_ai_model CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_rule CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_policy CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_event CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_event_type CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_assertion CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_vector CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_vector_type CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_fact_class_mapping CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_fact_class CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_relation CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_relation_type CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_context CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_context_type CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_source CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_property CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_entity CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_entity_type CASCADE CONSTRAINTS PURGE;
DROP TABLE tps_schema_migration CASCADE CONSTRAINTS PURGE;

WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
  l_remaining NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_remaining
    FROM user_objects
   WHERE object_name IN (
    'TPS_SCHEMA_MIGRATION','TPS_ENTITY_TYPE','TPS_ENTITY','TPS_PROPERTY','TPS_SOURCE',
    'TPS_CONTEXT_TYPE','TPS_CONTEXT','TPS_RELATION_TYPE','TPS_RELATION','TPS_D3KA_PKG',
    'TPS_FACT_CLASS','TPS_FACT_CLASS_MAPPING','TPS_VECTOR_TYPE','TPS_VECTOR','TPS_ASSERTION',
    'TPS_EVENT_TYPE','TPS_EVENT','TPS_POLICY','TPS_RULE','TPS_POLICY_ENGINE_PKG',
    'TPS_AI_MODEL','TPS_AI_AGENT','TPS_AI_TOOL','TPS_AI_DECISION','TPS_AUDIT_EVENT',
    'TPS_STATION','TPS_CHANNEL','TPS_PROGRAM','TPS_SCHEDULE','TPS_SCHEDULE_ITEM','TPS_MEDIA_ASSET',
    'TPS_CAMPAIGN','TPS_PLACEMENT','TPS_RIGHT_GRANT','TPS_RIGHTS_PKG',
    'TPS_AUDIENCE_SEGMENT','TPS_AUDIENCE_OBSERVATION','TPS_EDITORIAL_ITEM',
    'TPS_D3KA_ACTIVE_V','TPS_D3KA_HISTORY_V','TPS_D3KA_INVARIANT_VIOLATIONS_V','TPS_D3KA_COVERAGE_V',
    'TPS_GRAPH_NEIGHBORS_V','TPS_ENTITY_API_V','TPS_STATION_NOW_PROGRAMMING_V'
   );

  DBMS_OUTPUT.PUT_LINE('V0001_ROLLBACK_REMAINING_CORE_OBJECTS='||l_remaining);
  IF l_remaining<>0 THEN
    RAISE_APPLICATION_ERROR(-20902,'V0001_ROLLBACK=FAIL');
  END IF;
  DBMS_OUTPUT.PUT_LINE('V0001_ROLLBACK=PASS');
END;
/
