-- TPSDBCORE01 | CORE-08 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_vector_type (
    vector_type_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    type_code            VARCHAR2(120) NOT NULL,
    display_name         VARCHAR2(200) NOT NULL,
    distance_metric      VARCHAR2(30) DEFAULT 'COSINE' NOT NULL,
    description          VARCHAR2(1000),
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_vector_type_code UNIQUE (type_code),
    CONSTRAINT ck_tps_vector_metric CHECK (distance_metric IN ('COSINE','EUCLIDEAN','DOT','MANHATTAN','HAMMING'))
);
