/*=============================================================================
 @file              src/07-vector/700_tps_vector_type.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-08
 @workstream        WS-09 Vector semantics
 @source_state      SOURCE_READY_PENDING_RUNTIME_COMPATIBILITY_TEST
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before vector data; R3 after vector history/indexes depend on IDs
 @purpose           Define governed semantic-vector classes and intended distance metric for
                    multivector entity representations such as text, audio, music style,
                    audience affinity, editorial, brand, program and commercial embeddings.
 @business_impact   Allows one entity to have multiple purpose-specific semantic spaces without
                    overloading one generic embedding or altering TPS_ENTITY for each model/use case.
 @objects           Creates TPS_VECTOR_TYPE with PK/unique key/distance-metric check.
 @dependencies      None.
 @upstream          VECTOR-DICTIONARY, AI/ML architecture and approved embedding use cases.
 @downstream        TPS_VECTOR, similarity queries, ANN index design, Graph RAG and AI retrieval.
 @d3ka_role         VECTOR
 @d3ka_links        Defines V-space semantics attached to D3KA entity endpoints/context. VECTOR
                    represents semantic geometry and never replaces S/R/T relation structure.
 @ai_role           Embedding/retrieval metadata. Model/provider details are stored on TPS_VECTOR rows;
                    type ontology remains governed and model-independent where possible.
 @security          Vector type metadata non-secret. Underlying embeddings can leak semantic information;
                    access to TPS_VECTOR must inherit source-data classification.
 @performance       Small reference table. TYPE_CODE unique lookup; DISTANCE_METRIC is metadata and
                    is NOT automatically used by current query templates/index definitions.
 @transaction       DDL implicit commit on deployment.
 @idempotency       CREATE TABLE non-idempotent; TYPE_CODE provides stable identity.
 @failure_modes     Metric names are constrained by this source but actual Oracle operator/index support
                    for every listed metric must be certified on the installed 26ai service. Metadata
                    compatibility does not prove execution/index support.
 @rollback_recovery Before use controlled drop; after vector rows reference IDs, preserve/migrate taxonomy.
 @tests             tests/vector/V-001_vector_distance.sql; V-002_exact_topk.sql; V-003 ANN method.
 @evidence          CORE-08 vector model/metric evidence; CORE-17 performance; CORE-20 certification.
 @references        Oracle AI Vector Search User's Guide / VECTOR_DISTANCE documentation for 26ai.
 @links             docs/06-data-dictionary/VECTOR-DICTIONARY.md;
                    src/07-vector/710_tps_vector.sql;
                    src/07-vector/720_vector_similarity_queries.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full embedded documentation; DDL unchanged.
=============================================================================*/

-- One row = one governed semantic vector space/use class.
CREATE TABLE tps_vector_type (
    vector_type_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    type_code            VARCHAR2(120) NOT NULL,
    display_name         VARCHAR2(200) NOT NULL,
    -- Intended metric for this semantic space. Consumers must actually honor/validate it.
    distance_metric      VARCHAR2(30) DEFAULT 'COSINE' NOT NULL,
    description          VARCHAR2(1000),
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_vector_type_code UNIQUE (type_code),
    CONSTRAINT ck_tps_vector_metric CHECK (distance_metric IN ('COSINE','EUCLIDEAN','DOT','MANHATTAN','HAMMING'))
);
