/*=============================================================================
 @file              src/07-vector/710_tps_vector.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-08
 @workstream        WS-09 Vector semantics / WS-11 AI retrieval
 @source_state      SOURCE_READY_PENDING_RUNTIME_COMPATIBILITY_TEST
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before vector data; R3 after embeddings/history/indexes exist
 @purpose           Persist multiple versioned semantic embeddings per canonical entity and
                    vector type while recording model identity/version and source fingerprint.
 @business_impact   Supports semantic search/recommendation/Graph RAG across music, audio,
                    images, editorial, brands, programs, commercials and audience affinity
                    without replacing canonical relational/D3KA identity or relations.
 @objects           Creates TPS_VECTOR and relational index IX_TPS_VECTOR_ENTITY_TYPE.
 @dependencies      TPS_ENTITY, TPS_VECTOR_TYPE and Oracle VECTOR data type capability.
 @upstream          Governed embedding pipelines/models and source content fingerprints.
 @downstream        Exact/ANN similarity queries, Graph RAG, recommendations, AI analytics.
 @d3ka_role         VECTOR
 @d3ka_links        ENTITY_ID attaches V enrichment to a D3KA endpoint; VECTOR_TYPE_ID identifies
                    semantic space. Graph S/R/T remains authoritative for explicit relationships.
 @ai_role           Stores embeddings generated by versioned models. MODEL_KEY/MODEL_VERSION and
                    SOURCE_HASH_SHA256 support provenance/reproducibility; embedding alone is not fact.
 @security          Embeddings can encode sensitive source semantics. Apply access controls matching
                    source classification; do not assume vectors are anonymized. Model keys are metadata,
                    not credentials. No API keys/secrets belong in this table.
 @performance       Potentially high storage/CPU footprint. Entity/type/state index supports metadata lookup.
                    No vector ANN index is created here; exact similarity can be expensive. HNSW/IVF templates
                    exist separately and require recall/latency/capacity evidence before production use.
 @transaction       DDL implicit commit. Runtime vector writes caller-owned; no autonomous transactions.
 @idempotency       CREATE TABLE/INDEX non-idempotent. Current DDL does not define a natural uniqueness
                    constraint across entity/type/model/version/source hash, so embedding pipeline must enforce
                    idempotency until a deliberate database invariant is approved.
 @failure_modes     VECTOR capability unsupported, missing entity/type, invalid state, storage growth,
                    duplicate logical embeddings, DIMENSION_COUNT metadata disagreeing with actual VECTOR
                    dimension. Current DDL does NOT constrain DIMENSION_COUNT to EMBEDDING metadata; tests/
                    ingest validation must enforce consistency.
 @rollback_recovery Before data controlled drop. After embeddings are used, preserve model/source lineage;
                    stale/superseded state is preferred over destructive deletion except recovery workflows.
 @tests             tests/vector/V-001_vector_distance.sql; V-002_exact_topk.sql;
                    V-003_ann_recall_method.md; PERF-005_vector_exact.sql.
 @evidence          CORE-08 type/storage/search evidence; CORE-16 AI grounding; CORE-17 performance/capacity.
 @references        Oracle AI Vector Search User's Guide: VECTOR data type, VECTOR_DISTANCE, vector indexes.
 @links             src/07-vector/700_tps_vector_type.sql;
                    src/07-vector/720_vector_similarity_queries.sql;
                    src/21-indexes/2100_vector_hnsw_template.sql;
                    src/21-indexes/2110_vector_ivf_template.sql;
                    docs/07-ai-ml/AI-ML-RAG-AGENTS-MASTER-SPEC-v0.02.md
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full documentation/limits; DDL/index unchanged.
=============================================================================*/

-- One row = one versioned semantic embedding for one canonical entity in one vector space.
CREATE TABLE tps_vector (
    vector_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_id            NUMBER NOT NULL,
    vector_type_id       NUMBER NOT NULL,
    model_key            VARCHAR2(300) NOT NULL,
    model_version        VARCHAR2(200) NOT NULL,
    -- Fingerprint of source material used to derive the embedding when available.
    source_hash_sha256   VARCHAR2(64),
    -- Informational dimension metadata; current DDL does not enforce equality with VECTOR dimension.
    dimension_count      NUMBER,
    embedding            VECTOR NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_vector_entity FOREIGN KEY (entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_vector_type FOREIGN KEY (vector_type_id) REFERENCES tps_vector_type(vector_type_id),
    CONSTRAINT ck_tps_vector_state CHECK (state IN ('ACTIVE','STALE','SUPERSEDED','RETIRED'))
);

-- Relational metadata lookup index; this is not an ANN vector index.
CREATE INDEX ix_tps_vector_entity_type ON tps_vector(entity_id, vector_type_id, state);
