-- TPSDBCORE01 | CORE-08 | R1 ADDITIVE | NOT DEPLOYED
CREATE TABLE tps_vector (
    vector_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_id            NUMBER NOT NULL,
    vector_type_id       NUMBER NOT NULL,
    model_key            VARCHAR2(300) NOT NULL,
    model_version        VARCHAR2(200) NOT NULL,
    source_hash_sha256   VARCHAR2(64),
    dimension_count      NUMBER,
    embedding            VECTOR NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_vector_entity FOREIGN KEY (entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_vector_type FOREIGN KEY (vector_type_id) REFERENCES tps_vector_type(vector_type_id),
    CONSTRAINT ck_tps_vector_state CHECK (state IN ('ACTIVE','STALE','SUPERSEDED','RETIRED'))
);

CREATE INDEX ix_tps_vector_entity_type ON tps_vector(entity_id, vector_type_id, state);
