-- TPSDBCORE01 | CORE-08 | R1 ADDITIVE | NOT DEPLOYED
-- A vector belongs to exactly one canonical entity OR knowledge assertion.
CREATE TABLE tps_vector (
    vector_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_id            NUMBER,
    assertion_id         NUMBER,
    vector_type_id       NUMBER NOT NULL,
    model_key            VARCHAR2(300) NOT NULL,
    model_version        VARCHAR2(200) NOT NULL,
    source_hash_sha256   VARCHAR2(64),
    dimension_count      NUMBER,
    embedding            VECTOR NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_vector_entity FOREIGN KEY (entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_vector_assertion FOREIGN KEY (assertion_id) REFERENCES tps_assertion(assertion_id),
    CONSTRAINT fk_tps_vector_type FOREIGN KEY (vector_type_id) REFERENCES tps_vector_type(vector_type_id),
    CONSTRAINT ck_tps_vector_owner CHECK (
      (entity_id IS NOT NULL AND assertion_id IS NULL) OR
      (entity_id IS NULL AND assertion_id IS NOT NULL)
    ),
    CONSTRAINT ck_tps_vector_dimension CHECK (dimension_count IS NULL OR dimension_count > 0),
    CONSTRAINT ck_tps_vector_state CHECK (state IN ('ACTIVE','STALE','SUPERSEDED','RETIRED'))
);

CREATE INDEX ix_tps_vector_entity_type ON tps_vector(entity_id, vector_type_id, state);
CREATE INDEX ix_tps_vector_assertion_type ON tps_vector(assertion_id, vector_type_id, state);
