-- TPSDBCORE01 | CORE-10 | R1 | NOT DEPLOYED
CREATE TABLE tps_ai_model (
    ai_model_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    model_key            VARCHAR2(200) NOT NULL,
    provider_code        VARCHAR2(100) NOT NULL,
    provider_model_id    VARCHAR2(300) NOT NULL,
    model_version        VARCHAR2(200),
    model_class          VARCHAR2(40) NOT NULL,
    risk_class           VARCHAR2(30) DEFAULT 'MEDIUM' NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    attributes_json      JSON,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_ai_model_key UNIQUE(model_key),
    CONSTRAINT ck_tps_ai_model_class CHECK(model_class IN ('LLM','EMBEDDING','CLASSIFIER','RANKER','FORECAST','OTHER')),
    CONSTRAINT ck_tps_ai_model_state CHECK(state IN ('ACTIVE','DISABLED','DEPRECATED','RETIRED'))
);
