/*=============================================================================
 @file              src/11-ai/1100_tps_ai_model.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-10/16
 @workstream        WS-11 AI/ML/RAG/Agents
 @source_state      SOURCE_READY_WITH_LIMITATION
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before model metadata; R3 after decision/vector history references IDs
 @purpose           Register governed identities for AI/ML models used by LLM, embedding,
                    classification, ranking or forecasting capabilities, independent of secrets/credentials.
 @business_impact   Makes model/provider/version/risk lineage explicit so recommendations, embeddings
                    and AI decisions can be traced to the model configuration that produced them.
 @objects           Creates TPS_AI_MODEL with PK, unique MODEL_KEY and class/state checks.
 @dependencies      None.
 @upstream          Approved model/provider governance and model cards.
 @downstream        TPS_AI_AGENT, TPS_AI_DECISION, embedding/model lineage and certification.
 @d3ka_role         AI
 @d3ka_links        Model metadata explains AI/V transformations over D3KA knowledge but is not a D3KA fact by itself.
 @ai_role           Canonical registry of AI model identities/classes/provider references.
 @security          PROVIDER_MODEL_ID/MODEL_KEY are metadata; credentials, tokens and API keys are prohibited
                    in any column/ATTRIBUTES_JSON. Provider access is configured externally through approved mechanisms.
 @performance       Small registry table; MODEL_KEY unique lookup, provider/model/version filtering.
 @transaction       DDL implicit commit; runtime metadata writes governed/audited.
 @idempotency       CREATE TABLE non-idempotent; MODEL_KEY is stable natural identity.
 @failure_modes     Duplicate key, invalid MODEL_CLASS/STATE. RISK_CLASS currently has a default but NO CHECK
                    constraint; risk taxonomy must be validated by governance/reference tests before certification.
                    MODEL_VERSION may be NULL, which weakens reproducibility for providers/models without immutable IDs.
 @rollback_recovery Before use controlled drop; after decisions/vectors reference AI_MODEL_ID, preserve IDs/history.
 @tests             AI model/risk/version registry tests pending; AI-001 authority test uses adjacent agent metadata.
 @evidence          CORE-10 model governance; CORE-16 reproducibility/safety evidence.
 @references        Oracle Select AI/AI Agent documentation plus project model-governance policy.
 @links             docs/07-ai-ml/AI-ML-RAG-AGENTS-MASTER-SPEC-v0.02.md;
                    src/11-ai/1110_tps_ai_agent.sql; src/11-ai/1130_tps_ai_decision.sql;
                    src/07-vector/710_tps_vector.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full docs and risk/version gaps; DDL unchanged.
=============================================================================*/

-- One row = one governed AI/ML model identity; never store provider credentials here.
CREATE TABLE tps_ai_model (
    ai_model_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    model_key            VARCHAR2(200) NOT NULL,
    provider_code        VARCHAR2(100) NOT NULL,
    provider_model_id    VARCHAR2(300) NOT NULL,
    model_version        VARCHAR2(200),
    model_class          VARCHAR2(40) NOT NULL,
    -- Governance classification; current DDL does not constrain vocabulary beyond VARCHAR2.
    risk_class           VARCHAR2(30) DEFAULT 'MEDIUM' NOT NULL,
    state                VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    -- Non-secret model metadata only.
    attributes_json      JSON,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_ai_model_key UNIQUE(model_key),
    CONSTRAINT ck_tps_ai_model_class CHECK(model_class IN ('LLM','EMBEDDING','CLASSIFIER','RANKER','FORECAST','OTHER')),
    CONSTRAINT ck_tps_ai_model_state CHECK(state IN ('ACTIVE','DISABLED','DEPRECATED','RETIRED'))
);
