/*=============================================================================
 @file              src/11-ai/1110_tps_ai_agent.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-10/16
 @workstream        WS-11 AI/ML/RAG/Agents
 @source_state      SOURCE_READY_WITH_LIMITATION
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before agent metadata; R3 after decision history references IDs
 @purpose           Register corporate AI agent identities, optional model association, declared
                    authority class, lifecycle state and non-secret configuration metadata.
 @business_impact   Makes agent purpose/authority explicit for program direction, music, news,
                    commercial, audience, rights, compliance, archive and operations workflows.
 @objects           Creates TPS_AI_AGENT with PK, unique AGENT_KEY, model FK, authority/state checks.
 @dependencies      TPS_AI_MODEL.
 @upstream          Approved agent cards/governance and model registry.
 @downstream        TPS_AI_DECISION and external Oracle AI Agent configuration/templates.
 @d3ka_role         AI
 @d3ka_links        Agents consume/propose knowledge over D3KA/Graph/Vector; this row does not grant S/R/T authority.
 @ai_role           Corporate logical registry for agent identity and declared authority category.
 @security          Default STATE=DISABLED is fail-safe. AGENT_CONFIG_JSON must never contain credentials.
                    AUTHORITY_CLASS is metadata only; actual Oracle privileges, tool allowlists and policy engine
                    enforce real authority. BOUNDED_AUTOMATION requires explicit bounded action design/tests.
 @performance       Small registry; AGENT_KEY/model/state lookup.
 @transaction       DDL implicit commit; metadata maintenance governed/audited.
 @idempotency       CREATE TABLE non-idempotent; AGENT_KEY stable identity.
 @failure_modes     Missing model FK, invalid authority/state. AI_MODEL_ID may be NULL by design, so consumers must
                    not assume every agent has a fixed model. Metadata authority does not prevent a misconfigured
                    external agent from excessive access; actual privilege/tool controls remain mandatory.
 @rollback_recovery Preserve AGENT_ID once decision history exists; disable/suspend/retire rather than delete.
 @tests             tests/AI/AI-001_authority_classes.sql; AI-003_policy_boundary.sql;
                    AI-005 prompt/tool attack cases.
 @evidence          CORE-10 agent governance; CORE-16 authority-boundary/safety evidence.
 @references        Oracle DBMS_CLOUD_AI_AGENT documentation; project agent governance/model cards.
 @links             src/11-ai/1100_tps_ai_model.sql; src/11-ai/1130_tps_ai_decision.sql;
                    src/11-ai/1160_agent_program_director_template.sql;
                    docs/07-ai-ml/AI-ML-RAG-AGENTS-MASTER-SPEC-v0.02.md
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full documentation/authority semantics; DDL unchanged.
=============================================================================*/

CREATE TABLE tps_ai_agent (
    ai_agent_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    agent_key            VARCHAR2(200) NOT NULL,
    display_name         VARCHAR2(300) NOT NULL,
    ai_model_id          NUMBER,
    -- Declared governance class only; never substitute this column for actual privileges/policy enforcement.
    authority_class      VARCHAR2(40) DEFAULT 'ADVISORY' NOT NULL,
    -- Fail-safe default: registration does not activate an agent.
    state                VARCHAR2(30) DEFAULT 'DISABLED' NOT NULL,
    -- Non-secret logical configuration/model-card metadata.
    agent_config_json    JSON,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_ai_agent_key UNIQUE(agent_key),
    CONSTRAINT fk_tps_ai_agent_model FOREIGN KEY(ai_model_id) REFERENCES tps_ai_model(ai_model_id),
    CONSTRAINT ck_tps_ai_agent_authority CHECK(authority_class IN ('ADVISORY','BOUNDED_AUTOMATION','ANALYTICS_ONLY')),
    CONSTRAINT ck_tps_ai_agent_state CHECK(state IN ('DISABLED','ACTIVE','SUSPENDED','RETIRED'))
);
