-- TPSDBCORE01 | CORE-10 | R1 | NOT DEPLOYED
CREATE TABLE tps_ai_agent (
    ai_agent_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    agent_key            VARCHAR2(200) NOT NULL,
    display_name         VARCHAR2(300) NOT NULL,
    ai_model_id          NUMBER,
    authority_class      VARCHAR2(40) DEFAULT 'ADVISORY' NOT NULL,
    state                VARCHAR2(30) DEFAULT 'DISABLED' NOT NULL,
    agent_config_json    JSON,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_tps_ai_agent_key UNIQUE(agent_key),
    CONSTRAINT fk_tps_ai_agent_model FOREIGN KEY(ai_model_id) REFERENCES tps_ai_model(ai_model_id),
    CONSTRAINT ck_tps_ai_agent_authority CHECK(authority_class IN ('ADVISORY','BOUNDED_AUTOMATION','ANALYTICS_ONLY')),
    CONSTRAINT ck_tps_ai_agent_state CHECK(state IN ('DISABLED','ACTIVE','SUSPENDED','RETIRED'))
);
