-- TPSDBCORE01 | CORE-10/11 | R1 | NOT DEPLOYED
CREATE TABLE tps_ai_tool (
    ai_tool_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tool_key             VARCHAR2(200) NOT NULL,
    tool_class           VARCHAR2(50) NOT NULL,
    authority_class      VARCHAR2(50) NOT NULL,
    state                VARCHAR2(30) DEFAULT 'DISABLED' NOT NULL,
    tool_config_json     JSON,
    CONSTRAINT uk_tps_ai_tool_key UNIQUE(tool_key),
    CONSTRAINT ck_tps_ai_tool_state CHECK(state IN ('DISABLED','ACTIVE','SUSPENDED','RETIRED'))
);
