-- TPSDBCORE01 | CORE-10/12 | R1 | NOT DEPLOYED
CREATE TABLE tps_ai_decision (
    ai_decision_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ai_agent_id          NUMBER,
    ai_model_id          NUMBER,
    request_id           VARCHAR2(200),
    context_id           NUMBER,
    input_summary_json   JSON,
    retrieved_evidence_json JSON,
    output_json          JSON,
    confidence           NUMBER(5,4),
    policy_result        VARCHAR2(40),
    final_action         VARCHAR2(100),
    human_override       NUMBER(1) DEFAULT 0 NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_ai_decision_agent FOREIGN KEY(ai_agent_id) REFERENCES tps_ai_agent(ai_agent_id),
    CONSTRAINT fk_tps_ai_decision_model FOREIGN KEY(ai_model_id) REFERENCES tps_ai_model(ai_model_id),
    CONSTRAINT fk_tps_ai_decision_context FOREIGN KEY(context_id) REFERENCES tps_context(context_id),
    CONSTRAINT ck_tps_ai_decision_conf CHECK(confidence IS NULL OR (confidence >=0 AND confidence <=1)),
    CONSTRAINT ck_tps_ai_decision_override CHECK(human_override IN (0,1))
);
