/*=============================================================================
 @file              src/11-ai/1190_tps_ai_agent_tool.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-10/11/16/18
 @workstream        AI capability security / tool authorization
 @source_state      SOURCE_READY_PENDING_RUNTIME_COMPILE_TEST
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before grants; R2_STATEFUL once permissions control runtime
 @purpose           Persist explicit time-bounded permission mapping between a governed AI agent
                    and a governed AI tool/capability at READ, PROPOSE or EXECUTE_BOUNDED level.
 @business_impact   Prevents an AI agent from gaining authority merely because a tool exists or a
                    prompt says it may use it; capability becomes database-enforced configuration.
 @objects           Creates TPS_AI_AGENT_TOOL and lookup index.
 @dependencies      TPS_AI_AGENT, TPS_AI_TOOL.
 @upstream          AI governance/security administration.
 @downstream        TPS_AI_GUARD_PKG and every bounded AI tool wrapper.
 @d3ka_role         AI/POLICY/TEMPORAL
 @d3ka_links        Controls which AI actor may read/propose/execute against D3KA-backed capabilities.
 @ai_role           Primary database permission map for AI tooling.
 @security          High-sensitivity authorization metadata. Runtime agent cannot grant itself access.
 @performance       Small authorization table; lookup index supports agent/tool/mode/state/time check.
 @transaction       DDL implicit commit; grant maintenance caller-owned/audited.
 @idempotency       Current DDL permits historical multiple grants; active-window conflict must be governed/tested.
 @failure_modes     Missing agent/tool, invalid mode/state/time. Overlapping active grants are not prevented by
                    current DDL and require governance or future uniqueness logic.
 @rollback_recovery Revoke by state/time; preserve historical authorization records when audited.
 @tests             tests/ai-control/AIC-001_permission_guard.sql; AIC-002_bounded_execution.sql.
 @evidence          CORE-10/16/18 capability-boundary evidence.
 @references        Oracle AI Database 26ai PL/SQL/security principles; project least-privilege architecture.
 @links             src/11-ai/1110_tps_ai_agent.sql; src/11-ai/1120_tps_ai_tool.sql;
                    src/11-ai/1191_tps_ai_guard_pkg.pks
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — initial AI tool permission model.
=============================================================================*/

CREATE TABLE tps_ai_agent_tool (
    ai_agent_tool_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ai_agent_id         NUMBER NOT NULL,
    ai_tool_id          NUMBER NOT NULL,
    permission_mode     VARCHAR2(30) NOT NULL,
    state               VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    valid_from          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    valid_to            TIMESTAMP WITH TIME ZONE,
    attributes_json     JSON,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tps_ai_agent_tool_agent FOREIGN KEY(ai_agent_id) REFERENCES tps_ai_agent(ai_agent_id),
    CONSTRAINT fk_tps_ai_agent_tool_tool FOREIGN KEY(ai_tool_id) REFERENCES tps_ai_tool(ai_tool_id),
    CONSTRAINT ck_tps_ai_agent_tool_mode CHECK(permission_mode IN ('READ','PROPOSE','EXECUTE_BOUNDED')),
    CONSTRAINT ck_tps_ai_agent_tool_state CHECK(state IN ('ACTIVE','SUSPENDED','REVOKED','EXPIRED')),
    CONSTRAINT ck_tps_ai_agent_tool_time CHECK(valid_to IS NULL OR valid_to > valid_from)
);

CREATE INDEX ix_tps_ai_agent_tool_lookup
    ON tps_ai_agent_tool(ai_agent_id, ai_tool_id, permission_mode, state, valid_from, valid_to);
