-- TPSDBCORE01 | event fabric | R1 | NOT DEPLOYED
CREATE TABLE tps_event_type (
    event_type_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_code           VARCHAR2(120) NOT NULL,
    display_name         VARCHAR2(200) NOT NULL,
    retention_class      VARCHAR2(50) DEFAULT 'STANDARD' NOT NULL,
    description          VARCHAR2(1000),
    CONSTRAINT uk_tps_event_type_code UNIQUE(event_code)
);
