/*=============================================================================
 @file              src/09-event/900_tps_event_type.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-07/09/12/14
 @workstream        Event fabric / temporal history / audit
 @source_state      SOURCE_READY
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before use; R3 after event history references IDs
 @purpose           Define stable event-type identities and retention classes for the
                    corporate event fabric, separate from individual event occurrences.
 @business_impact   Standardizes history for program, media, audience, content, service and
                    AI-related events across all stations/applications.
 @objects           Creates TPS_EVENT_TYPE with primary key and unique EVENT_CODE.
 @dependencies      None.
 @upstream          EVENT-DICTIONARY and approved domain/retention architecture.
 @downstream        TPS_EVENT, analytics, history, audit, ML and recommendations.
 @d3ka_role         EVENT/TEMPORAL
 @d3ka_links        Events may observe/change D3KA-linked entities and provide temporal evidence;
                    an event is not automatically a D3KA relationship.
 @ai_role           AI may consume or emit governed event records; event ontology remains governed.
 @security          No secrets. Retention classification is governance-sensitive.
 @performance       Small reference table; EVENT_CODE unique lookup.
 @transaction       DDL implicit commit when deployed.
 @idempotency       CREATE TABLE non-idempotent; EVENT_CODE is the stable natural key.
 @failure_modes     Duplicate EVENT_CODE. RETENTION_CLASS vocabulary is not constrained by
                    current DDL and therefore requires governed reference/retention rules.
 @rollback_recovery Before use controlled drop; after events exist preserve IDs and migrate.
 @tests             Event reference/FK tests are pending.
 @evidence          Event ontology and retention evidence for relevant CORE gates.
 @references        Oracle AI Database 26ai SQL Language Reference; project retention policy.
 @links             docs/06-data-dictionary/EVENT-DICTIONARY.md;
                    src/09-event/910_tps_event.sql
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full documentation; DDL unchanged.
=============================================================================*/

CREATE TABLE tps_event_type (
    event_type_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_code           VARCHAR2(120) NOT NULL,
    display_name         VARCHAR2(200) NOT NULL,
    -- Retention vocabulary is governed outside this DDL and must be validated before use.
    retention_class      VARCHAR2(50) DEFAULT 'STANDARD' NOT NULL,
    description          VARCHAR2(1000),
    CONSTRAINT uk_tps_event_type_code UNIQUE(event_code)
);
