/*=============================================================================
 @file              src/09-event/910_tps_event.sql
 @project           TPS MEDIA INTELLIGENCE FABRIC CORE
 @database          TPSDBCORE01 / TPS_INTELLIGENCE_CORE_01
 @environment       PRODUCTION
 @oracle_target     Oracle AI Database 26ai
 @gate              CORE-07/09/12/14
 @workstream        Event fabric / temporal history / provenance / audit
 @source_state      SOURCE_READY_WITH_LIMITATION
 @production_state  NOT_DEPLOYED
 @reversibility     R1_ADDITIVE before event data; R3_TRANSFORMATIVE after event history exists
 @purpose           Persist immutable-style event occurrences with type, optional subject/context/source,
                    correlation, event time, record time and JSON payload for historical reconstruction.
 @business_impact   Provides common event history for programming, media playback, audience sessions,
                    commercial delivery, failures, publications, entity changes and AI decisions.
 @objects           Creates TPS_EVENT plus subject-time and type-time indexes.
 @dependencies      TPS_EVENT_TYPE, TPS_ENTITY, TPS_CONTEXT, TPS_SOURCE.
 @upstream          Domain/event producers and governed ingestion services.
 @downstream        Historical analytics, temporal graph reconstruction, ML, audit, recommendations,
                    incident correlation and future event-driven automation.
 @d3ka_role         EVENT/TEMPORAL/PROVENANCE/CONTEXT
 @d3ka_links        SUBJECT_ENTITY_ID links event to D3KA identity; CONTEXT_ID=C; SOURCE_ID=E;
                    EVENT_TIME=occurrence time while RECORDED_AT=knowledge/ingest time To.
 @ai_role           AI can consume events or emit explicitly governed AI decision/recommendation events.
                    Event presence is evidence/history, not automatic authority to execute an action.
 @security          PAYLOAD_JSON may contain sensitive audience/operational/editorial information;
                    event access, retention and redaction must follow data classification. Secrets prohibited.
 @performance       Expected high-volume append-oriented table. Subject/time and type/time indexes support
                    principal historical access paths but add write/storage cost. Partitioning/retention strategy
                    is not implemented in this source and must be designed before large-scale production ingestion.
 @transaction       DDL implicit commit; runtime event inserts should participate in caller transaction unless
                    an explicitly designed durable event boundary is approved. No autonomous transaction here.
 @idempotency       CREATE TABLE/index non-idempotent. Current schema does not enforce unique CORRELATION_ID or
                    producer event key; duplicate event ingestion is possible unless producer/ingest contract
                    supplies deduplication. This is a certification gap for at-least-once delivery scenarios.
 @failure_modes     Missing FK/type/context/source, invalid JSON, storage growth, duplicate logical events,
                    unbounded payload/retention behavior. EVENT_TIME vs RECORDED_AT must not be conflated.
 @rollback_recovery Before data controlled drop. Once historical events exist, treat ledger as retained history;
                    purge/archive only under retention policy and recovery evidence, not ad-hoc rollback.
 @tests             Dedicated event insert/FK/idempotency/retention/performance tests pending.
 @evidence          Event/temporal/audit evidence; CORE-17 performance; CORE-19 recovery/retention;
                    CORE-20 certification.
 @references        Oracle AI Database 26ai SQL Language Reference: JSON, timestamps, indexes, constraints.
 @links             src/09-event/900_tps_event_type.sql; src/02-kernel/230_tps_source.sql;
                    docs/06-data-dictionary/EVENT-DICTIONARY.md;
                    docs/14-compliance/RETENTION-RIGHTS-COMPLIANCE.md
 @owner             TPS MEDIA DATABASE ENGINEERING
 @change_history    v0.02 2026-09-01 — full documentation/idempotency-retention gaps; DDL unchanged.
=============================================================================*/

-- One row = one event occurrence. EVENT_TIME is when it happened; RECORDED_AT is when DB learned it.
CREATE TABLE tps_event (
    event_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_type_id        NUMBER NOT NULL,
    subject_entity_id    NUMBER,
    context_id           NUMBER,
    source_id            NUMBER,
    -- Cross-system/workflow correlation metadata; current DDL does not make it unique.
    correlation_id       VARCHAR2(200),
    event_time           TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    payload_json         JSON,
    CONSTRAINT fk_tps_event_type FOREIGN KEY(event_type_id) REFERENCES tps_event_type(event_type_id),
    CONSTRAINT fk_tps_event_subject FOREIGN KEY(subject_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_event_context FOREIGN KEY(context_id) REFERENCES tps_context(context_id),
    CONSTRAINT fk_tps_event_source FOREIGN KEY(source_id) REFERENCES tps_source(source_id)
);

CREATE INDEX ix_tps_event_subject_time ON tps_event(subject_entity_id,event_time);
CREATE INDEX ix_tps_event_type_time ON tps_event(event_type_id,event_time);
