-- TPSDBCORE01 | event fabric | R1 | NOT DEPLOYED
CREATE TABLE tps_event (
    event_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_type_id        NUMBER NOT NULL,
    subject_entity_id    NUMBER,
    context_id           NUMBER,
    source_id            NUMBER,
    correlation_id       VARCHAR2(200),
    event_time           TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    payload_json         JSON,
    CONSTRAINT fk_tps_event_type FOREIGN KEY(event_type_id) REFERENCES tps_event_type(event_type_id),
    CONSTRAINT fk_tps_event_subject FOREIGN KEY(subject_entity_id) REFERENCES tps_entity(entity_id),
    CONSTRAINT fk_tps_event_context FOREIGN KEY(context_id) REFERENCES tps_context(context_id),
    CONSTRAINT fk_tps_event_source FOREIGN KEY(source_id) REFERENCES tps_source(source_id)
);
CREATE INDEX ix_tps_event_subject_time ON tps_event(subject_entity_id,event_time);
CREATE INDEX ix_tps_event_type_time ON tps_event(event_type_id,event_time);
