/* TPSDBCORE01 V0003 PRECHECK — READ ONLY */
SET SERVEROUTPUT ON

DECLARE
    l_missing NUMBER;
    l_existing NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_missing
    FROM (
        SELECT 'TPS_ENTITY' n FROM dual UNION ALL
        SELECT 'TPS_PROGRAM' FROM dual UNION ALL
        SELECT 'TPS_SCHEDULE' FROM dual UNION ALL
        SELECT 'TPS_SCHEDULE_ITEM' FROM dual UNION ALL
        SELECT 'TPS_MEDIA_ASSET' FROM dual UNION ALL
        SELECT 'TPS_CAMPAIGN' FROM dual UNION ALL
        SELECT 'TPS_PLACEMENT' FROM dual UNION ALL
        SELECT 'TPS_RIGHTS_PKG' FROM dual UNION ALL
        SELECT 'TPS_PROGRAMMING_PKG' FROM dual
    ) req
    WHERE NOT EXISTS (
        SELECT 1 FROM user_objects u
        WHERE u.object_name=req.n AND u.status='VALID'
    );

    SELECT COUNT(*) INTO l_existing
    FROM user_objects
    WHERE object_name IN (
        'TPS_CONTENT_RATING',
        'TPS_PROGRAMMING_RULE_PROFILE',
        'TPS_PROGRAMMING_RULES_PKG',
        'TPS_COMMERCIAL_PKG',
        'TRG_TPS_SCHEDULE_POLICY_GUARD'
    );

    IF l_missing <> 0 THEN
        DBMS_OUTPUT.PUT_LINE('V0003_PRECHECK=FAIL BASE_MISSING='||l_missing);
        RAISE_APPLICATION_ERROR(-20981,'V0003_BASE_DEPENDENCY_MISSING');
    END IF;

    IF l_existing <> 0 THEN
        DBMS_OUTPUT.PUT_LINE('V0003_PRECHECK=FAIL TARGET_OBJECTS_ALREADY_EXIST='||l_existing);
        RAISE_APPLICATION_ERROR(-20980,'V0003_TARGET_OBJECTS_ALREADY_EXIST');
    END IF;

    DBMS_OUTPUT.PUT_LINE('V0003_PRECHECK=PASS');
END;
/
