-- TPSDBCORE01 | REFERENCE DATA | R2 DML | NOT DEPLOYED
MERGE INTO tps_entity_type t
USING (
  SELECT 'PERSON' code, 'Person' name FROM dual UNION ALL
  SELECT 'ORGANIZATION','Organization' FROM dual UNION ALL
  SELECT 'NETWORK','Media Network' FROM dual UNION ALL
  SELECT 'BRAND','Brand' FROM dual UNION ALL
  SELECT 'RADIO_STATION','Radio Station' FROM dual UNION ALL
  SELECT 'TV_STATION','TV Station' FROM dual UNION ALL
  SELECT 'AFFILIATE','Affiliate' FROM dual UNION ALL
  SELECT 'REPEATER','Repeater' FROM dual UNION ALL
  SELECT 'CHANNEL','Channel' FROM dual UNION ALL
  SELECT 'PROGRAM','Program' FROM dual UNION ALL
  SELECT 'SONG','Song' FROM dual UNION ALL
  SELECT 'RECORDING','Recording' FROM dual UNION ALL
  SELECT 'ALBUM','Album' FROM dual UNION ALL
  SELECT 'AUDIO','Audio' FROM dual UNION ALL
  SELECT 'VIDEO','Video' FROM dual UNION ALL
  SELECT 'IMAGE','Image' FROM dual UNION ALL
  SELECT 'PODCAST','Podcast' FROM dual UNION ALL
  SELECT 'EPISODE','Episode' FROM dual UNION ALL
  SELECT 'NEWS_ARTICLE','News Article' FROM dual UNION ALL
  SELECT 'REPORT','Report' FROM dual UNION ALL
  SELECT 'INTERVIEW','Interview' FROM dual UNION ALL
  SELECT 'COMMERCIAL','Commercial' FROM dual UNION ALL
  SELECT 'JINGLE','Jingle' FROM dual UNION ALL
  SELECT 'PROMO','Promo' FROM dual UNION ALL
  SELECT 'LIVE_FEED','Live Feed' FROM dual UNION ALL
  SELECT 'MEDIA_ASSET','Media Asset' FROM dual UNION ALL
  SELECT 'ADVERTISER','Advertiser' FROM dual UNION ALL
  SELECT 'RIGHTS_HOLDER','Rights Holder' FROM dual UNION ALL
  SELECT 'CAMPAIGN','Campaign' FROM dual UNION ALL
  SELECT 'AUDIENCE_SEGMENT','Audience Segment' FROM dual UNION ALL
  SELECT 'CONTRACT','Contract' FROM dual UNION ALL
  SELECT 'RIGHT','Right' FROM dual UNION ALL
  SELECT 'LOCATION','Location' FROM dual UNION ALL
  SELECT 'REGION','Region' FROM dual UNION ALL
  SELECT 'EVENT','Event' FROM dual UNION ALL
  SELECT 'DEVICE','Device' FROM dual UNION ALL
  SELECT 'SERVICE','Service' FROM dual UNION ALL
  SELECT 'SYSTEM','System' FROM dual UNION ALL
  SELECT 'AI_ENTITY','AI Entity' FROM dual
) s
ON (t.type_code=s.code)
WHEN MATCHED THEN UPDATE SET t.display_name=s.name, t.updated_at=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT(type_code,display_name) VALUES(s.code,s.name);
