-- TPSDBCORE01 | REFERENCE DATA | R2 DML | NOT DEPLOYED
MERGE INTO tps_relation_type t
USING (
  SELECT code, display_name,
         CASE WHEN code IN ('LICENSED_BY','AUTHORIZED_FOR','PROHIBITED_IN','SCHEDULED_ON','TARGETS','SPONSORED_BY') THEN 1 ELSE 0 END AS policy_sensitive,
         CASE WHEN code IN ('MENTIONS','REFERENCES','DERIVED_FROM','GENERATED_BY','AI_RECOMMENDED') THEN 1 ELSE 0 END AS requires_provenance
  FROM (
    SELECT 'OWNS' code,'Owns' display_name FROM dual UNION ALL SELECT 'OPERATES','Operates' FROM dual UNION ALL
    SELECT 'MANAGES','Manages' FROM dual UNION ALL SELECT 'BELONGS_TO','Belongs To' FROM dual UNION ALL
    SELECT 'AFFILIATED_WITH','Affiliated With' FROM dual UNION ALL SELECT 'REPEATS','Repeats' FROM dual UNION ALL
    SELECT 'BROADCASTS','Broadcasts' FROM dual UNION ALL SELECT 'PRESENTS','Presents' FROM dual UNION ALL
    SELECT 'PRODUCES','Produces' FROM dual UNION ALL SELECT 'DIRECTS','Directs' FROM dual UNION ALL
    SELECT 'PERFORMS','Performs' FROM dual UNION ALL SELECT 'COMPOSED','Composed' FROM dual UNION ALL
    SELECT 'AUTHORED','Authored' FROM dual UNION ALL SELECT 'FEATURES','Features' FROM dual UNION ALL
    SELECT 'PLAYED_ON','Played On' FROM dual UNION ALL SELECT 'SCHEDULED_ON','Scheduled On' FROM dual UNION ALL
    SELECT 'TARGETS','Targets' FROM dual UNION ALL SELECT 'SPONSORED_BY','Sponsored By' FROM dual UNION ALL
    SELECT 'LICENSED_BY','Licensed By' FROM dual UNION ALL SELECT 'AUTHORIZED_FOR','Authorized For' FROM dual UNION ALL
    SELECT 'PROHIBITED_IN','Prohibited In' FROM dual UNION ALL SELECT 'AVAILABLE_IN','Available In' FROM dual UNION ALL
    SELECT 'POPULAR_IN','Popular In' FROM dual UNION ALL SELECT 'SIMILAR_TO','Similar To' FROM dual UNION ALL
    SELECT 'INFLUENCED_BY','Influenced By' FROM dual UNION ALL SELECT 'MENTIONS','Mentions' FROM dual UNION ALL
    SELECT 'REFERENCES','References' FROM dual UNION ALL SELECT 'DERIVED_FROM','Derived From' FROM dual UNION ALL
    SELECT 'GENERATED_BY','Generated By' FROM dual UNION ALL SELECT 'CLASSIFIED_AS','Classified As' FROM dual UNION ALL
    SELECT 'RECOMMENDED_FOR','Recommended For' FROM dual UNION ALL SELECT 'MASTER_OF','Master Of' FROM dual UNION ALL
    SELECT 'PROXY_OF','Proxy Of' FROM dual UNION ALL SELECT 'TRANSCODED_FROM','Transcoded From' FROM dual UNION ALL
    SELECT 'THUMBNAIL_OF','Thumbnail Of' FROM dual UNION ALL SELECT 'AUDIO_OF','Audio Of' FROM dual UNION ALL
    SELECT 'VIDEO_OF','Video Of' FROM dual UNION ALL SELECT 'SUBTITLE_OF','Subtitle Of' FROM dual UNION ALL
    SELECT 'TRANSCRIPT_OF','Transcript Of' FROM dual UNION ALL SELECT 'SERVES_REGION','Serves Region' FROM dual UNION ALL
    SELECT 'COMPETES_WITH','Competes With' FROM dual UNION ALL SELECT 'PROMOTES','Promotes' FROM dual UNION ALL
    SELECT 'AI_RECOMMENDED','AI Recommended' FROM dual
  )
) s
ON (t.relation_code=s.code)
WHEN MATCHED THEN UPDATE SET t.display_name=s.display_name,t.policy_sensitive=s.policy_sensitive,t.requires_provenance=s.requires_provenance
WHEN NOT MATCHED THEN INSERT(relation_code,display_name,policy_sensitive,requires_provenance)
VALUES(s.code,s.display_name,s.policy_sensitive,s.requires_provenance);
