-- TPSDBCORE01 | D3KA COVERAGE MAPPINGS | R2 DML | NOT DEPLOYED
MERGE INTO tps_fact_class_mapping m
USING (
  SELECT fc.fact_class_id,
         rt.relation_type_id,
         'D3KA_RELATION' representation_class,
         'IMPLEMENTED' implementation_status,
         'TPS_RELATION/TPS_MEDIA_KNOWLEDGE_GRAPH' implementation_ref
  FROM tps_fact_class fc
  JOIN tps_relation_type rt ON rt.relation_code = CASE fc.fact_class_key
    WHEN 'ORG_OWNS_NETWORK' THEN 'OWNS'
    WHEN 'NETWORK_OWNS_STATION' THEN 'OWNS'
    WHEN 'STATION_BROADCASTS_CHANNEL' THEN 'BROADCASTS'
    WHEN 'STATION_AFFILIATED_WITH_NETWORK' THEN 'AFFILIATED_WITH'
    WHEN 'REPEATER_REPEATS_STATION' THEN 'REPEATS'
    WHEN 'STATION_SERVES_REGION' THEN 'SERVES_REGION'
    WHEN 'PERSON_PRESENTS_PROGRAM' THEN 'PRESENTS'
    WHEN 'PERSON_PRODUCES_PROGRAM' THEN 'PRODUCES'
    WHEN 'PROGRAM_SCHEDULED_ON_CHANNEL' THEN 'SCHEDULED_ON'
    WHEN 'CONTENT_PLAYED_ON_CHANNEL' THEN 'PLAYED_ON'
    WHEN 'ARTIST_PERFORMS_SONG' THEN 'PERFORMS'
    WHEN 'SONG_FEATURES_ARTIST' THEN 'FEATURES'
    WHEN 'ALBUM_FEATURES_RECORDING' THEN 'FEATURES'
    WHEN 'ASSET_MASTER_OF_CONTENT' THEN 'MASTER_OF'
    WHEN 'ASSET_TRANSCODED_FROM_ASSET' THEN 'TRANSCODED_FROM'
    WHEN 'CAMPAIGN_TARGETS_AUDIENCE' THEN 'TARGETS'
    WHEN 'CAMPAIGN_SPONSORED_BY_ADVERTISER' THEN 'SPONSORED_BY'
    WHEN 'COMMERCIAL_SCHEDULED_ON_CHANNEL' THEN 'SCHEDULED_ON'
    WHEN 'CONTENT_LICENSED_BY_HOLDER' THEN 'LICENSED_BY'
    WHEN 'CONTENT_AUTHORIZED_FOR_REGION' THEN 'AUTHORIZED_FOR'
    WHEN 'CONTENT_PROHIBITED_IN_REGION' THEN 'PROHIBITED_IN'
    WHEN 'CONTENT_AVAILABLE_IN_REGION' THEN 'AVAILABLE_IN'
    WHEN 'CONTENT_POPULAR_IN_SEGMENT' THEN 'POPULAR_IN'
    WHEN 'CONTENT_RECOMMENDED_FOR_SEGMENT' THEN 'RECOMMENDED_FOR'
    WHEN 'CONTENT_SIMILAR_TO_CONTENT' THEN 'SIMILAR_TO'
    WHEN 'ARTICLE_MENTIONS_ENTITY' THEN 'MENTIONS'
    WHEN 'ARTICLE_REFERENCES_SOURCE' THEN 'REFERENCES'
    WHEN 'ASSERTION_DERIVED_FROM_SOURCE' THEN 'DERIVED_FROM'
    WHEN 'CONTENT_GENERATED_BY_AI' THEN 'GENERATED_BY'
    WHEN 'ENTITY_CLASSIFIED_AS_ENTITY' THEN 'CLASSIFIED_AS'
  END
  WHERE fc.d3ka_eligible=1
) s
ON (m.fact_class_id=s.fact_class_id AND m.relation_type_id=s.relation_type_id AND m.representation_class='D3KA_RELATION')
WHEN MATCHED THEN UPDATE SET m.implementation_status=s.implementation_status,m.implementation_ref=s.implementation_ref
WHEN NOT MATCHED THEN INSERT(fact_class_id,relation_type_id,representation_class,implementation_status,implementation_ref)
VALUES(s.fact_class_id,s.relation_type_id,s.representation_class,s.implementation_status,s.implementation_ref);
