-- V0004 PRECHECK — READ ONLY
SET SERVEROUTPUT ON
DECLARE
  l_missing NUMBER := 0;
  l_invalid NUMBER := 0;
  l_ref_missing NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO l_missing
  FROM (
    SELECT 'TPS_ENTITY_TYPE' object_name,'TABLE' object_type FROM dual UNION ALL
    SELECT 'TPS_ENTITY','TABLE' FROM dual UNION ALL
    SELECT 'TPS_STATION','TABLE' FROM dual UNION ALL
    SELECT 'TPS_CHANNEL','TABLE' FROM dual UNION ALL
    SELECT 'TPS_PROGRAM','TABLE' FROM dual UNION ALL
    SELECT 'TPS_MEDIA_ASSET','TABLE' FROM dual UNION ALL
    SELECT 'TPS_RELATION_TYPE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_RELATION','TABLE' FROM dual UNION ALL
    SELECT 'TPS_SOURCE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_RIGHT_GRANT','TABLE' FROM dual UNION ALL
    SELECT 'TPS_SCHEDULE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_SCHEDULE_ITEM','TABLE' FROM dual UNION ALL
    SELECT 'TPS_PROGRAMMING_RULE_PROFILE','TABLE' FROM dual UNION ALL
    SELECT 'TPS_D3KA_PKG','PACKAGE' FROM dual UNION ALL
    SELECT 'TPS_RIGHTS_PKG','PACKAGE' FROM dual UNION ALL
    SELECT 'TPS_PROGRAMMING_PKG','PACKAGE' FROM dual UNION ALL
    SELECT 'TPS_PROGRAMMING_RULES_PKG','PACKAGE' FROM dual UNION ALL
    SELECT 'TPS_CONTINUITY_PKG','PACKAGE' FROM dual
  ) e
  WHERE NOT EXISTS (
    SELECT 1 FROM user_objects u
     WHERE u.object_name=e.object_name
       AND u.object_type=e.object_type
  );

  SELECT COUNT(*) INTO l_invalid
    FROM user_objects
   WHERE object_name IN (
      'TPS_D3KA_PKG','TPS_RIGHTS_PKG','TPS_PROGRAMMING_PKG',
      'TPS_PROGRAMMING_RULES_PKG','TPS_CONTINUITY_PKG'
   )
     AND object_type IN ('PACKAGE','PACKAGE BODY')
     AND status <> 'VALID';

  SELECT COUNT(*) INTO l_ref_missing
  FROM (
    SELECT 'ET:NETWORK' k FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM tps_entity_type WHERE type_code='NETWORK' AND lifecycle_state='ACTIVE')
    UNION ALL SELECT 'ET:RADIO_STATION' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM tps_entity_type WHERE type_code='RADIO_STATION' AND lifecycle_state='ACTIVE')
    UNION ALL SELECT 'ET:TV_STATION' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM tps_entity_type WHERE type_code='TV_STATION' AND lifecycle_state='ACTIVE')
    UNION ALL SELECT 'ET:CHANNEL' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM tps_entity_type WHERE type_code='CHANNEL' AND lifecycle_state='ACTIVE')
    UNION ALL SELECT 'ET:PROGRAM' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM tps_entity_type WHERE type_code='PROGRAM' AND lifecycle_state='ACTIVE')
    UNION ALL SELECT 'ET:MEDIA_ASSET' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM tps_entity_type WHERE type_code='MEDIA_ASSET' AND lifecycle_state='ACTIVE')
    UNION ALL SELECT 'ET:SYSTEM' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM tps_entity_type WHERE type_code='SYSTEM' AND lifecycle_state='ACTIVE')
    UNION ALL SELECT 'RT:AFFILIATED_WITH' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM tps_relation_type WHERE relation_code='AFFILIATED_WITH' AND lifecycle_state='ACTIVE')
  );

  DBMS_OUTPUT.PUT_LINE('V0004_MISSING_OBJECTS='||l_missing);
  DBMS_OUTPUT.PUT_LINE('V0004_INVALID_DEPENDENCIES='||l_invalid);
  DBMS_OUTPUT.PUT_LINE('V0004_MISSING_REFERENCE_ROWS='||l_ref_missing);

  IF l_missing<>0 OR l_invalid<>0 OR l_ref_missing<>0 THEN
    RAISE_APPLICATION_ERROR(-20920,'V0004_PRECHECK=FAIL');
  END IF;

  DBMS_OUTPUT.PUT_LINE('V0004_PRECHECK=PASS');
END;
/
